modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Tynoxs/BuildersDelight/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://curseforge.com/minecraft/mc-mods/builders-delight-forge"
updateJSONURL=""
logoFile="logo.png"
credits=""
authors="Tynoxs"
description="A mod that aims to add some more variety to minecraft by adding new blocks & items, and also trying to keep the vanilla feeling."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
