package com.tynoxs.buildersdelight.datagen.loot;

import com.tynoxs.buildersdelight.content.init.BdBlocks;
import net.minecraft.advancements.critereon.StatePropertiesPredicate;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.state.properties.SlabType;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraftforge.registries.RegistryObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.BiConsumer;

public class BdBlockLootTables extends BlockLootSubProvider {
    public List<Block> list = new ArrayList<>();

    public BdBlockLootTables() {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), new HashMap<>());
    }

    @Override
    protected void generate() {
        registerDropSelf(BdBlocks.ACACIA_FRAME_1.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_2.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_3.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_4.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_5.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_6.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_7.get());
        registerDropSelf(BdBlocks.ACACIA_FRAME_8.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_1.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_2.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_3.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_4.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_5.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_6.get());
        registerDropSelf(BdBlocks.ACACIA_PLANKS_7.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_1.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_2.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_3.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_4.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_5.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_6.get());
        registerDropSelf(BdBlocks.ACACIA_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_1.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_2.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_3.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_4.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_5.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_6.get());
        registerSlabItemTable(BdBlocks.ACACIA_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.BIRCH_FRAME_1.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_2.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_3.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_4.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_5.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_6.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_7.get());
        registerDropSelf(BdBlocks.BIRCH_FRAME_8.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_1.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_2.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_3.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_4.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_5.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_6.get());
        registerDropSelf(BdBlocks.BIRCH_PLANKS_7.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_1.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_2.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_3.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_4.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_5.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_6.get());
        registerDropSelf(BdBlocks.BIRCH_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_1.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_2.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_3.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_4.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_5.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_6.get());
        registerSlabItemTable(BdBlocks.BIRCH_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.CHERRY_FRAME_1.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_2.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_3.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_4.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_5.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_6.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_7.get());
        registerDropSelf(BdBlocks.CHERRY_FRAME_8.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_1.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_2.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_3.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_4.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_5.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_6.get());
        registerDropSelf(BdBlocks.CHERRY_PLANKS_7.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_1.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_2.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_3.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_4.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_5.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_6.get());
        registerDropSelf(BdBlocks.CHERRY_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_1.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_2.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_3.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_4.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_5.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_6.get());
        registerSlabItemTable(BdBlocks.CHERRY_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.CHERRY_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.CRIMSON_FRAME_1.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_2.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_3.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_4.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_5.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_6.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_7.get());
        registerDropSelf(BdBlocks.CRIMSON_FRAME_8.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_1.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_2.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_3.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_4.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_5.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_6.get());
        registerDropSelf(BdBlocks.CRIMSON_PLANKS_7.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_1.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_2.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_3.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_4.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_5.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_6.get());
        registerDropSelf(BdBlocks.CRIMSON_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_1.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_2.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_3.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_4.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_5.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_6.get());
        registerSlabItemTable(BdBlocks.CRIMSON_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.DARK_OAK_FRAME_1.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_2.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_3.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_4.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_5.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_6.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_7.get());
        registerDropSelf(BdBlocks.DARK_OAK_FRAME_8.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_1.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_2.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_3.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_4.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_5.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_6.get());
        registerDropSelf(BdBlocks.DARK_OAK_PLANKS_7.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_1.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_2.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_3.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_4.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_5.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_6.get());
        registerDropSelf(BdBlocks.DARK_OAK_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_1.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_2.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_3.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_4.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_5.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_6.get());
        registerSlabItemTable(BdBlocks.DARK_OAK_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.JUNGLE_FRAME_1.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_2.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_3.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_4.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_5.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_6.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_7.get());
        registerDropSelf(BdBlocks.JUNGLE_FRAME_8.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_1.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_2.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_3.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_4.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_5.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_6.get());
        registerDropSelf(BdBlocks.JUNGLE_PLANKS_7.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_1.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_2.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_3.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_4.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_5.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_6.get());
        registerDropSelf(BdBlocks.JUNGLE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.JUNGLE_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.MANGROVE_FRAME_1.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_2.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_3.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_4.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_5.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_6.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_7.get());
        registerDropSelf(BdBlocks.MANGROVE_FRAME_8.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_1.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_2.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_3.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_4.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_5.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_6.get());
        registerDropSelf(BdBlocks.MANGROVE_PLANKS_7.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_1.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_2.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_3.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_4.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_5.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_6.get());
        registerDropSelf(BdBlocks.MANGROVE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.MANGROVE_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.MANGROVE_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.OAK_FRAME_1.get());
        registerDropSelf(BdBlocks.OAK_FRAME_2.get());
        registerDropSelf(BdBlocks.OAK_FRAME_3.get());
        registerDropSelf(BdBlocks.OAK_FRAME_4.get());
        registerDropSelf(BdBlocks.OAK_FRAME_5.get());
        registerDropSelf(BdBlocks.OAK_FRAME_6.get());
        registerDropSelf(BdBlocks.OAK_FRAME_7.get());
        registerDropSelf(BdBlocks.OAK_FRAME_8.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_1.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_2.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_3.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_4.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_5.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_6.get());
        registerDropSelf(BdBlocks.OAK_PLANKS_7.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_1.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_2.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_3.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_4.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_5.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_6.get());
        registerDropSelf(BdBlocks.OAK_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_1.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_2.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_3.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_4.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_5.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_6.get());
        registerSlabItemTable(BdBlocks.OAK_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.SPRUCE_FRAME_1.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_2.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_3.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_4.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_5.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_6.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_7.get());
        registerDropSelf(BdBlocks.SPRUCE_FRAME_8.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_1.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_2.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_3.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_4.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_5.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_6.get());
        registerDropSelf(BdBlocks.SPRUCE_PLANKS_7.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_1.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_2.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_3.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_4.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_5.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_6.get());
        registerDropSelf(BdBlocks.SPRUCE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.SPRUCE_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.WARPED_FRAME_1.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_2.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_3.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_4.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_5.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_6.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_7.get());
        registerDropSelf(BdBlocks.WARPED_FRAME_8.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_1.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_2.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_3.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_4.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_5.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_6.get());
        registerDropSelf(BdBlocks.WARPED_PLANKS_7.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_1.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_2.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_3.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_4.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_5.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_6.get());
        registerDropSelf(BdBlocks.WARPED_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_1.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_2.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_3.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_4.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_5.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_6.get());
        registerSlabItemTable(BdBlocks.WARPED_SLAB_7.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_7.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_8.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_7.get());
        registerDropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_8.get());

        registerDropSelf(BdBlocks.AMETHYST_BLOCK_1.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_2.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_3.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_4.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_5.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_6.get());
        registerDropSelf(BdBlocks.AMETHYST_BLOCK_7.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_1.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_2.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_3.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_4.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_5.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_6.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_7.get());
        registerDropSelf(BdBlocks.AMETHYST_STAIRS_8.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_1.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_2.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_3.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_4.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_5.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_6.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_7.get());
        registerSlabItemTable(BdBlocks.AMETHYST_SLAB_8.get());

        registerDropSelf(BdBlocks.ANDESITE_1.get());
        registerDropSelf(BdBlocks.ANDESITE_2.get());
        registerDropSelf(BdBlocks.ANDESITE_3.get());
        registerDropSelf(BdBlocks.ANDESITE_4.get());
        registerDropSelf(BdBlocks.ANDESITE_5.get());
        registerDropSelf(BdBlocks.ANDESITE_6.get());
        registerDropSelf(BdBlocks.ANDESITE_7.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_1.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_2.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_3.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_4.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_5.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_6.get());
        registerDropSelf(BdBlocks.ANDESITE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.ANDESITE_SLAB_7.get());

        registerDropSelf(BdBlocks.BLACKSTONE_1.get());
        registerDropSelf(BdBlocks.BLACKSTONE_2.get());
        registerDropSelf(BdBlocks.BLACKSTONE_3.get());
        registerDropSelf(BdBlocks.BLACKSTONE_4.get());
        registerDropSelf(BdBlocks.BLACKSTONE_5.get());
        registerDropSelf(BdBlocks.BLACKSTONE_6.get());

        registerDropSelf(BdBlocks.BRICKS_1.get());
        registerDropSelf(BdBlocks.BRICKS_2.get());
        registerDropSelf(BdBlocks.BRICKS_3.get());
        registerDropSelf(BdBlocks.BRICKS_4.get());
        registerDropSelf(BdBlocks.BRICKS_5.get());
        registerDropSelf(BdBlocks.BRICKS_6.get());
        registerDropSelf(BdBlocks.BRICKS_7.get());
        registerDropSelf(BdBlocks.BRICKS_8.get());
        registerDropSelf(BdBlocks.BRICKS_9.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_1.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_2.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_3.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_4.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_5.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_6.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_7.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_8.get());
        registerDropSelf(BdBlocks.BRICK_STAIRS_9.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_1.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_2.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_3.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_4.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_5.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_6.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_7.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_8.get());
        registerSlabItemTable(BdBlocks.BRICK_SLAB_9.get());

        registerDropSelf(BdBlocks.CALCITE_2.get());
        registerDropSelf(BdBlocks.CALCITE_3.get());
        registerDropSelf(BdBlocks.CALCITE_4.get());
        registerDropSelf(BdBlocks.CALCITE_5.get());
        registerDropSelf(BdBlocks.CALCITE_6.get());
        registerDropSelf(BdBlocks.CALCITE_7.get());
        registerDropSelf(BdBlocks.CALCITE_8.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_1.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_2.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_3.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_4.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_5.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_6.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_7.get());
        registerDropSelf(BdBlocks.CALCITE_STAIRS_8.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_7.get());
        registerSlabItemTable(BdBlocks.CALCITE_SLAB_8.get());

        registerDropSelf(BdBlocks.COBBLESTONE_1.get());
        registerDropSelf(BdBlocks.COBBLESTONE_2.get());
        registerDropSelf(BdBlocks.COBBLESTONE_3.get());
        registerDropSelf(BdBlocks.COBBLESTONE_4.get());
        registerDropSelf(BdBlocks.COBBLESTONE_5.get());
        registerDropSelf(BdBlocks.COBBLESTONE_6.get());
        registerDropSelf(BdBlocks.COBBLESTONE_7.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_1.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_2.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_3.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_4.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_5.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_6.get());
        registerDropSelf(BdBlocks.COBBLESTONE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.COBBLESTONE_SLAB_7.get());

        registerDropSelf(BdBlocks.DEEPSLATE_1.get());
        registerDropSelf(BdBlocks.DEEPSLATE_2.get());
        registerDropSelf(BdBlocks.DEEPSLATE_3.get());
        registerDropSelf(BdBlocks.DEEPSLATE_4.get());
        registerDropSelf(BdBlocks.DEEPSLATE_5.get());
        registerDropSelf(BdBlocks.DEEPSLATE_STAIRS_1.get());
        registerDropSelf(BdBlocks.DEEPSLATE_STAIRS_2.get());
        registerDropSelf(BdBlocks.DEEPSLATE_STAIRS_3.get());
        registerDropSelf(BdBlocks.DEEPSLATE_STAIRS_4.get());
        registerDropSelf(BdBlocks.DEEPSLATE_STAIRS_5.get());
        registerSlabItemTable(BdBlocks.DEEPSLATE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.DEEPSLATE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.DEEPSLATE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.DEEPSLATE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.DEEPSLATE_SLAB_5.get());

        registerDropSelf(BdBlocks.DIORITE_1.get());
        registerDropSelf(BdBlocks.DIORITE_2.get());
        registerDropSelf(BdBlocks.DIORITE_3.get());
        registerDropSelf(BdBlocks.DIORITE_4.get());
        registerDropSelf(BdBlocks.DIORITE_5.get());
        registerDropSelf(BdBlocks.DIORITE_6.get());
        registerDropSelf(BdBlocks.DIORITE_7.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_1.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_2.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_3.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_4.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_5.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_6.get());
        registerDropSelf(BdBlocks.DIORITE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.DIORITE_SLAB_7.get());

        registerDropSelf(BdBlocks.DRIPSTONE_1.get());
        registerDropSelf(BdBlocks.DRIPSTONE_2.get());
        registerDropSelf(BdBlocks.DRIPSTONE_3.get());
        registerDropSelf(BdBlocks.DRIPSTONE_4.get());
        registerDropSelf(BdBlocks.DRIPSTONE_5.get());
        registerDropSelf(BdBlocks.DRIPSTONE_6.get());
        registerDropSelf(BdBlocks.DRIPSTONE_7.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_1.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_2.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_3.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_4.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_5.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_6.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_7.get());
        registerDropSelf(BdBlocks.DRIPSTONE_STAIRS_8.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_7.get());
        registerSlabItemTable(BdBlocks.DRIPSTONE_SLAB_8.get());

        registerDropSelf(BdBlocks.GILDED_BLACKSTONE_1.get());
        registerDropSelf(BdBlocks.GILDED_BLACKSTONE_2.get());
        registerDropSelf(BdBlocks.GILDED_BLACKSTONE_3.get());
        registerDropSelf(BdBlocks.GILDED_BLACKSTONE_4.get());

        registerDropSelf(BdBlocks.GILDED_NETHER_BRICKS_1.get());
        registerDropSelf(BdBlocks.GILDED_NETHER_BRICKS_2.get());
        registerDropSelf(BdBlocks.GILDED_NETHER_BRICKS_3.get());
        registerDropSelf(BdBlocks.GILDED_NETHER_BRICKS_4.get());

        registerDropWhenSilkTouch(BdBlocks.GLASS_1.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_2.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_3.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_4.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_5.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_6.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_7.get());

        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_1.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_2.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_3.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_4.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_5.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_6.get());
        registerDropWhenSilkTouch(BdBlocks.GLASS_PANE_7.get());

        registerDropSelf(BdBlocks.GRANITE_1.get());
        registerDropSelf(BdBlocks.GRANITE_2.get());
        registerDropSelf(BdBlocks.GRANITE_3.get());
        registerDropSelf(BdBlocks.GRANITE_4.get());
        registerDropSelf(BdBlocks.GRANITE_5.get());
        registerDropSelf(BdBlocks.GRANITE_6.get());
        registerDropSelf(BdBlocks.GRANITE_7.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_1.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_2.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_3.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_4.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_5.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_6.get());
        registerDropSelf(BdBlocks.GRANITE_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_6.get());
        registerSlabItemTable(BdBlocks.GRANITE_SLAB_7.get());

        registerDropSelf(BdBlocks.INDUSTRIAL_1.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_2.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_3.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_4.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_5.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_6.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_7.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_8.get());

        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_1.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_2.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_3.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_4.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_5.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_6.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_7.get());
        registerDropSelf(BdBlocks.INDUSTRIAL_FLAT_8.get());

        registerDropSelf(BdBlocks.LABORATORY_1.get());
        registerDropSelf(BdBlocks.LABORATORY_2.get());
        registerDropSelf(BdBlocks.LABORATORY_3.get());

        registerDropSelf(BdBlocks.NETHER_BRICKS_1.get());
        registerDropSelf(BdBlocks.NETHER_BRICKS_2.get());
        registerDropSelf(BdBlocks.NETHER_BRICKS_3.get());
        registerDropSelf(BdBlocks.NETHER_BRICKS_4.get());
        registerDropSelf(BdBlocks.NETHER_BRICKS_5.get());
        registerDropSelf(BdBlocks.NETHER_BRICKS_6.get());

        registerDropSelf(BdBlocks.PRISMARINE_1.get());
        registerDropSelf(BdBlocks.PRISMARINE_2.get());
        registerDropSelf(BdBlocks.PRISMARINE_3.get());
        registerDropSelf(BdBlocks.PRISMARINE_4.get());
        registerDropSelf(BdBlocks.PRISMARINE_5.get());
        registerDropSelf(BdBlocks.PRISMARINE_6.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_1.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_2.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_3.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_4.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_5.get());
        registerDropSelf(BdBlocks.PRISMARINE_STAIRS_6.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.PRISMARINE_SLAB_6.get());

        registerDropSelf(BdBlocks.SANDSTONE_1.get());
        registerDropSelf(BdBlocks.SANDSTONE_2.get());
        registerDropSelf(BdBlocks.SANDSTONE_3.get());
        registerDropSelf(BdBlocks.SANDSTONE_4.get());
        registerDropSelf(BdBlocks.SANDSTONE_5.get());
        registerDropSelf(BdBlocks.SANDSTONE_6.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_1.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_2.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_3.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_4.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_5.get());
        registerDropSelf(BdBlocks.SANDSTONE_STAIRS_6.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_1.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_2.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_3.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_4.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_5.get());
        registerSlabItemTable(BdBlocks.SANDSTONE_SLAB_6.get());

        registerDropSelf(BdBlocks.STONE_BRICKS_1.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_2.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_3.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_4.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_5.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_6.get());
        registerDropSelf(BdBlocks.STONE_BRICKS_7.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_1.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_2.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_3.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_4.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_5.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_6.get());
        registerDropSelf(BdBlocks.STONE_BRICK_STAIRS_7.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_1.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_2.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_3.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_4.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_5.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_6.get());
        registerSlabItemTable(BdBlocks.STONE_BRICK_SLAB_7.get());

        registerDropSelf(BdBlocks.TUFF_1.get());
        registerDropSelf(BdBlocks.TUFF_2.get());
        registerDropSelf(BdBlocks.TUFF_3.get());
        registerDropSelf(BdBlocks.TUFF_4.get());
        registerDropSelf(BdBlocks.TUFF_5.get());
        registerDropSelf(BdBlocks.TUFF_6.get());
        registerDropSelf(BdBlocks.TUFF_7.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_1.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_2.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_3.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_4.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_5.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_6.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_7.get());
        registerDropSelf(BdBlocks.TUFF_STAIRS_8.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_1.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_2.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_3.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_4.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_5.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_6.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_7.get());
        registerSlabItemTable(BdBlocks.TUFF_SLAB_8.get());

        registerDropSelf(BdBlocks.WARNING_STRIPES_1.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_2.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_3.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_4.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_5.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_6.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_7.get());
        registerDropSelf(BdBlocks.WARNING_STRIPES_8.get());

    }

    public void registerDropSelf(Block block) {
        list.add(block);
        dropSelf(block);
    }

    public void registerDropWhenSilkTouch(Block block) {
        list.add(block);
        dropWhenSilkTouch(block);
    }

    protected void registerSlabItemTable(Block p_124291_) {
        list.add(p_124291_);
        this.add(p_124291_, LootTable.lootTable().withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
                .add(applyExplosionDecay(p_124291_, LootItem.lootTableItem(p_124291_).apply(SetItemCountFunction.setCount(ConstantValue.exactly(2.0F))
                        .when(LootItemBlockStatePropertyCondition.hasBlockStateProperties(p_124291_).setProperties(StatePropertiesPredicate.Builder.properties().hasProperty(SlabBlock.TYPE, SlabType.DOUBLE))))))));
    }

    // Override and ignore the missing loot table error
    @Override
    public void generate(BiConsumer<ResourceLocation, LootTable.Builder> p_249322_) {
        this.generate();
        Set<ResourceLocation> set = new HashSet<>();

        for (Block block : list) {
            if (block.isEnabled(this.enabledFeatures)) {
                ResourceLocation resourcelocation = block.getLootTable();
                if (resourcelocation != BuiltInLootTables.EMPTY && set.add(resourcelocation)) {
                    LootTable.Builder loottable$builder = this.map.remove(resourcelocation);
                    if (loottable$builder == null) {
                        continue;
                    }

                    p_249322_.accept(resourcelocation, loottable$builder);
                }
            }
        }
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return BdBlocks.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
    }
}
