package com.tynoxs.buildersdelight.datagen.loot;

import com.tynoxs.buildersdelight.content.init.BdBlocks;
import net.minecraft.data.loot.BlockLoot;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.RegistryObject;

public class BdBlockLootTables extends BlockLoot {

    @Override
    protected void addTables() {
        this.dropSelf(BdBlocks.ACACIA_FRAME_1.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_2.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_3.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_4.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_5.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_6.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_7.get());
        this.dropSelf(BdBlocks.ACACIA_FRAME_8.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_1.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_2.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_3.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_4.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_5.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_6.get());
        this.dropSelf(BdBlocks.ACACIA_PLANKS_7.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_1.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_2.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_3.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_4.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_5.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_6.get());
        this.dropSelf(BdBlocks.ACACIA_STAIRS_7.get());
        this.add(BdBlocks.ACACIA_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ACACIA_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.ACACIA_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.BIRCH_FRAME_1.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_2.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_3.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_4.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_5.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_6.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_7.get());
        this.dropSelf(BdBlocks.BIRCH_FRAME_8.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_1.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_2.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_3.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_4.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_5.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_6.get());
        this.dropSelf(BdBlocks.BIRCH_PLANKS_7.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_1.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_2.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_3.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_4.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_5.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_6.get());
        this.dropSelf(BdBlocks.BIRCH_STAIRS_7.get());
        this.add(BdBlocks.BIRCH_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BIRCH_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.BIRCH_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.CRIMSON_FRAME_1.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_2.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_3.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_4.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_5.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_6.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_7.get());
        this.dropSelf(BdBlocks.CRIMSON_FRAME_8.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_1.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_2.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_3.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_4.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_5.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_6.get());
        this.dropSelf(BdBlocks.CRIMSON_PLANKS_7.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_1.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_2.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_3.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_4.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_5.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_6.get());
        this.dropSelf(BdBlocks.CRIMSON_STAIRS_7.get());
        this.add(BdBlocks.CRIMSON_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CRIMSON_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.CRIMSON_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.DARK_OAK_FRAME_1.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_2.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_3.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_4.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_5.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_6.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_7.get());
        this.dropSelf(BdBlocks.DARK_OAK_FRAME_8.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_1.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_2.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_3.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_4.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_5.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_6.get());
        this.dropSelf(BdBlocks.DARK_OAK_PLANKS_7.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_1.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_2.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_3.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_4.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_5.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_6.get());
        this.dropSelf(BdBlocks.DARK_OAK_STAIRS_7.get());
        this.add(BdBlocks.DARK_OAK_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DARK_OAK_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.DARK_OAK_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.JUNGLE_FRAME_1.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_2.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_3.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_4.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_5.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_6.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_7.get());
        this.dropSelf(BdBlocks.JUNGLE_FRAME_8.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_1.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_2.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_3.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_4.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_5.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_6.get());
        this.dropSelf(BdBlocks.JUNGLE_PLANKS_7.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_1.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_2.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_3.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_4.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_5.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_6.get());
        this.dropSelf(BdBlocks.JUNGLE_STAIRS_7.get());
        this.add(BdBlocks.JUNGLE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.JUNGLE_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.JUNGLE_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.OAK_FRAME_1.get());
        this.dropSelf(BdBlocks.OAK_FRAME_2.get());
        this.dropSelf(BdBlocks.OAK_FRAME_3.get());
        this.dropSelf(BdBlocks.OAK_FRAME_4.get());
        this.dropSelf(BdBlocks.OAK_FRAME_5.get());
        this.dropSelf(BdBlocks.OAK_FRAME_6.get());
        this.dropSelf(BdBlocks.OAK_FRAME_7.get());
        this.dropSelf(BdBlocks.OAK_FRAME_8.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_1.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_2.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_3.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_4.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_5.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_6.get());
        this.dropSelf(BdBlocks.OAK_PLANKS_7.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_1.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_2.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_3.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_4.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_5.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_6.get());
        this.dropSelf(BdBlocks.OAK_STAIRS_7.get());
        this.add(BdBlocks.OAK_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.OAK_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.OAK_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.SPRUCE_FRAME_1.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_2.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_3.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_4.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_5.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_6.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_7.get());
        this.dropSelf(BdBlocks.SPRUCE_FRAME_8.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_1.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_2.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_3.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_4.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_5.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_6.get());
        this.dropSelf(BdBlocks.SPRUCE_PLANKS_7.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_1.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_2.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_3.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_4.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_5.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_6.get());
        this.dropSelf(BdBlocks.SPRUCE_STAIRS_7.get());
        this.add(BdBlocks.SPRUCE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SPRUCE_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.SPRUCE_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.WARPED_FRAME_1.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_2.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_3.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_4.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_5.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_6.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_7.get());
        this.dropSelf(BdBlocks.WARPED_FRAME_8.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_1.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_2.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_3.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_4.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_5.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_6.get());
        this.dropSelf(BdBlocks.WARPED_PLANKS_7.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_1.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_2.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_3.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_4.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_5.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_6.get());
        this.dropSelf(BdBlocks.WARPED_STAIRS_7.get());
        this.add(BdBlocks.WARPED_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.WARPED_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_7.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_8.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_7.get());
        this.dropWhenSilkTouch(BdBlocks.WARPED_GLASS_PANE_8.get());

        this.dropSelf(BdBlocks.AMETHYST_BLOCK_1.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_2.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_3.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_4.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_5.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_6.get());
        this.dropSelf(BdBlocks.AMETHYST_BLOCK_7.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_1.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_2.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_3.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_4.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_5.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_6.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_7.get());
        this.dropSelf(BdBlocks.AMETHYST_STAIRS_8.get());
        this.add(BdBlocks.AMETHYST_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.AMETHYST_SLAB_8.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.ANDESITE_1.get());
        this.dropSelf(BdBlocks.ANDESITE_2.get());
        this.dropSelf(BdBlocks.ANDESITE_3.get());
        this.dropSelf(BdBlocks.ANDESITE_4.get());
        this.dropSelf(BdBlocks.ANDESITE_5.get());
        this.dropSelf(BdBlocks.ANDESITE_6.get());
        this.dropSelf(BdBlocks.ANDESITE_7.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_1.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_2.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_3.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_4.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_5.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_6.get());
        this.dropSelf(BdBlocks.ANDESITE_STAIRS_7.get());
        this.add(BdBlocks.ANDESITE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.ANDESITE_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.BLACKSTONE_1.get());
        this.dropSelf(BdBlocks.BLACKSTONE_2.get());
        this.dropSelf(BdBlocks.BLACKSTONE_3.get());
        this.dropSelf(BdBlocks.BLACKSTONE_4.get());
        this.dropSelf(BdBlocks.BLACKSTONE_5.get());
        this.dropSelf(BdBlocks.BLACKSTONE_6.get());

        this.dropSelf(BdBlocks.BRICKS_1.get());
        this.dropSelf(BdBlocks.BRICKS_2.get());
        this.dropSelf(BdBlocks.BRICKS_3.get());
        this.dropSelf(BdBlocks.BRICKS_4.get());
        this.dropSelf(BdBlocks.BRICKS_5.get());
        this.dropSelf(BdBlocks.BRICKS_6.get());
        this.dropSelf(BdBlocks.BRICKS_7.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_1.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_2.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_3.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_4.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_5.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_6.get());
        this.dropSelf(BdBlocks.BRICK_STAIRS_7.get());
        this.add(BdBlocks.BRICK_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.BRICK_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.CALCITE_2.get());
        this.dropSelf(BdBlocks.CALCITE_3.get());
        this.dropSelf(BdBlocks.CALCITE_4.get());
        this.dropSelf(BdBlocks.CALCITE_5.get());
        this.dropSelf(BdBlocks.CALCITE_6.get());
        this.dropSelf(BdBlocks.CALCITE_7.get());
        this.dropSelf(BdBlocks.CALCITE_8.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_1.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_2.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_3.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_4.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_5.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_6.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_7.get());
        this.dropSelf(BdBlocks.CALCITE_STAIRS_8.get());
        this.add(BdBlocks.CALCITE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.CALCITE_SLAB_8.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.COBBLESTONE_1.get());
        this.dropSelf(BdBlocks.COBBLESTONE_2.get());
        this.dropSelf(BdBlocks.COBBLESTONE_3.get());
        this.dropSelf(BdBlocks.COBBLESTONE_4.get());
        this.dropSelf(BdBlocks.COBBLESTONE_5.get());
        this.dropSelf(BdBlocks.COBBLESTONE_6.get());
        this.dropSelf(BdBlocks.COBBLESTONE_7.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_1.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_2.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_3.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_4.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_5.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_6.get());
        this.dropSelf(BdBlocks.COBBLESTONE_STAIRS_7.get());
        this.add(BdBlocks.COBBLESTONE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.COBBLESTONE_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.DEEPSLATE_1.get());
        this.dropSelf(BdBlocks.DEEPSLATE_2.get());
        this.dropSelf(BdBlocks.DEEPSLATE_3.get());
        this.dropSelf(BdBlocks.DEEPSLATE_4.get());
        this.dropSelf(BdBlocks.DEEPSLATE_5.get());
        this.dropSelf(BdBlocks.DEEPSLATE_STAIRS_1.get());
        this.dropSelf(BdBlocks.DEEPSLATE_STAIRS_2.get());
        this.dropSelf(BdBlocks.DEEPSLATE_STAIRS_3.get());
        this.dropSelf(BdBlocks.DEEPSLATE_STAIRS_4.get());
        this.dropSelf(BdBlocks.DEEPSLATE_STAIRS_5.get());
        this.add(BdBlocks.DEEPSLATE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DEEPSLATE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DEEPSLATE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DEEPSLATE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DEEPSLATE_SLAB_5.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.DIORITE_1.get());
        this.dropSelf(BdBlocks.DIORITE_2.get());
        this.dropSelf(BdBlocks.DIORITE_3.get());
        this.dropSelf(BdBlocks.DIORITE_4.get());
        this.dropSelf(BdBlocks.DIORITE_5.get());
        this.dropSelf(BdBlocks.DIORITE_6.get());
        this.dropSelf(BdBlocks.DIORITE_7.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_1.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_2.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_3.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_4.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_5.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_6.get());
        this.dropSelf(BdBlocks.DIORITE_STAIRS_7.get());
        this.add(BdBlocks.DIORITE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DIORITE_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.DRIPSTONE_1.get());
        this.dropSelf(BdBlocks.DRIPSTONE_2.get());
        this.dropSelf(BdBlocks.DRIPSTONE_3.get());
        this.dropSelf(BdBlocks.DRIPSTONE_4.get());
        this.dropSelf(BdBlocks.DRIPSTONE_5.get());
        this.dropSelf(BdBlocks.DRIPSTONE_6.get());
        this.dropSelf(BdBlocks.DRIPSTONE_7.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_1.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_2.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_3.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_4.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_5.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_6.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_7.get());
        this.dropSelf(BdBlocks.DRIPSTONE_STAIRS_8.get());
        this.add(BdBlocks.DRIPSTONE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.DRIPSTONE_SLAB_8.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.GILDED_BLACKSTONE_1.get());
        this.dropSelf(BdBlocks.GILDED_BLACKSTONE_2.get());
        this.dropSelf(BdBlocks.GILDED_BLACKSTONE_3.get());
        this.dropSelf(BdBlocks.GILDED_BLACKSTONE_4.get());

        this.dropSelf(BdBlocks.GILDED_NETHER_BRICKS_1.get());
        this.dropSelf(BdBlocks.GILDED_NETHER_BRICKS_2.get());
        this.dropSelf(BdBlocks.GILDED_NETHER_BRICKS_3.get());
        this.dropSelf(BdBlocks.GILDED_NETHER_BRICKS_4.get());

        this.dropWhenSilkTouch(BdBlocks.GLASS_1.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_2.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_3.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_4.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_5.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_6.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_7.get());

        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_1.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_2.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_3.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_4.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_5.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_6.get());
        this.dropWhenSilkTouch(BdBlocks.GLASS_PANE_7.get());

        this.dropSelf(BdBlocks.GRANITE_1.get());
        this.dropSelf(BdBlocks.GRANITE_2.get());
        this.dropSelf(BdBlocks.GRANITE_3.get());
        this.dropSelf(BdBlocks.GRANITE_4.get());
        this.dropSelf(BdBlocks.GRANITE_5.get());
        this.dropSelf(BdBlocks.GRANITE_6.get());
        this.dropSelf(BdBlocks.GRANITE_7.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_1.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_2.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_3.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_4.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_5.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_6.get());
        this.dropSelf(BdBlocks.GRANITE_STAIRS_7.get());
        this.add(BdBlocks.GRANITE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.GRANITE_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.INDUSTRIAL_1.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_2.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_3.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_4.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_5.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_6.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_7.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_8.get());

        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_1.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_2.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_3.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_4.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_5.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_6.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_7.get());
        this.dropSelf(BdBlocks.INDUSTRIAL_FLAT_8.get());

        this.dropSelf(BdBlocks.LABORATORY_1.get());
        this.dropSelf(BdBlocks.LABORATORY_2.get());
        this.dropSelf(BdBlocks.LABORATORY_3.get());

        this.dropSelf(BdBlocks.NETHER_BRICKS_1.get());
        this.dropSelf(BdBlocks.NETHER_BRICKS_2.get());
        this.dropSelf(BdBlocks.NETHER_BRICKS_3.get());
        this.dropSelf(BdBlocks.NETHER_BRICKS_4.get());
        this.dropSelf(BdBlocks.NETHER_BRICKS_5.get());
        this.dropSelf(BdBlocks.NETHER_BRICKS_6.get());

        this.dropSelf(BdBlocks.PRISMARINE_1.get());
        this.dropSelf(BdBlocks.PRISMARINE_2.get());
        this.dropSelf(BdBlocks.PRISMARINE_3.get());
        this.dropSelf(BdBlocks.PRISMARINE_4.get());
        this.dropSelf(BdBlocks.PRISMARINE_5.get());
        this.dropSelf(BdBlocks.PRISMARINE_6.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_1.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_2.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_3.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_4.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_5.get());
        this.dropSelf(BdBlocks.PRISMARINE_STAIRS_6.get());
        this.add(BdBlocks.PRISMARINE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.PRISMARINE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.PRISMARINE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.PRISMARINE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.PRISMARINE_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.PRISMARINE_SLAB_6.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.SANDSTONE_1.get());
        this.dropSelf(BdBlocks.SANDSTONE_2.get());
        this.dropSelf(BdBlocks.SANDSTONE_3.get());
        this.dropSelf(BdBlocks.SANDSTONE_4.get());
        this.dropSelf(BdBlocks.SANDSTONE_5.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_1.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_2.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_3.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_4.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_5.get());
        this.dropSelf(BdBlocks.SANDSTONE_STAIRS_6.get());
        this.add(BdBlocks.SANDSTONE_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SANDSTONE_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SANDSTONE_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SANDSTONE_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.SANDSTONE_SLAB_5.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.STONE_BRICKS_1.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_2.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_3.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_4.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_5.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_6.get());
        this.dropSelf(BdBlocks.STONE_BRICKS_7.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_1.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_2.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_3.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_4.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_5.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_6.get());
        this.dropSelf(BdBlocks.STONE_BRICK_STAIRS_7.get());
        this.add(BdBlocks.STONE_BRICK_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.STONE_BRICK_SLAB_7.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.TUFF_1.get());
        this.dropSelf(BdBlocks.TUFF_2.get());
        this.dropSelf(BdBlocks.TUFF_3.get());
        this.dropSelf(BdBlocks.TUFF_4.get());
        this.dropSelf(BdBlocks.TUFF_5.get());
        this.dropSelf(BdBlocks.TUFF_6.get());
        this.dropSelf(BdBlocks.TUFF_7.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_1.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_2.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_3.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_4.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_5.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_6.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_7.get());
        this.dropSelf(BdBlocks.TUFF_STAIRS_8.get());
        this.add(BdBlocks.TUFF_SLAB_1.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_2.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_3.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_4.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_5.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_6.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_7.get(), BlockLoot::createSlabItemTable);
        this.add(BdBlocks.TUFF_SLAB_8.get(), BlockLoot::createSlabItemTable);

        this.dropSelf(BdBlocks.WARNING_STRIPES_1.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_2.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_3.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_4.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_5.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_6.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_7.get());
        this.dropSelf(BdBlocks.WARNING_STRIPES_8.get());

    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return BdBlocks.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
    }
}
