package com.tynoxs.buildersdelight.datagen.providers;

import com.tynoxs.buildersdelight.content.block.custom.BlockInteractive;
import com.tynoxs.buildersdelight.content.init.BdBlocks;
import com.tynoxs.buildersdelight.datagen.blockstate.BdBlockStateCreator;
import net.minecraft.data.PackOutput;
import net.minecraft.world.level.block.*;
import net.minecraftforge.common.data.ExistingFileHelper;

public class BdBlockStateProvider extends BdBlockStateCreator {
    public BdBlockStateProvider(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
        simpleBlock(BdBlocks.ACACIA_FRAME_1.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_2.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_3.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_4.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_5.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_6.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_7.get());
        simpleBlock(BdBlocks.ACACIA_FRAME_8.get());
        simpleBlock(BdBlocks.ACACIA_GLASS_1.get());
        topSideBlock(BdBlocks.ACACIA_GLASS_2.get(), blockTexture(BdBlocks.ACACIA_GLASS_2.get()), blockTexture(BdBlocks.ACACIA_GLASS_2.get()));
        topSideBlock(BdBlocks.ACACIA_GLASS_3.get(), blockTexture(BdBlocks.ACACIA_GLASS_3.get()), blockTexture(BdBlocks.ACACIA_GLASS_3.get()));
        simpleBlock(BdBlocks.ACACIA_GLASS_4.get());
        topSideBlock(BdBlocks.ACACIA_GLASS_5.get(), blockTexture(BdBlocks.ACACIA_GLASS_5.get()), blockTexture(BdBlocks.ACACIA_GLASS_5.get()));
        topSideBlock(BdBlocks.ACACIA_GLASS_6.get(), blockTexture(BdBlocks.ACACIA_GLASS_6.get()), blockTexture(BdBlocks.ACACIA_GLASS_6.get()));
        topSideBlock(BdBlocks.ACACIA_GLASS_7.get(), blockTexture(BdBlocks.ACACIA_GLASS_7.get()), blockTexture(BdBlocks.ACACIA_GLASS_7.get()));
        simpleBlock(BdBlocks.ACACIA_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_1.get(), blockTexture(BdBlocks.ACACIA_GLASS_1.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_2.get(), blockTexture(BdBlocks.ACACIA_GLASS_2.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_3.get(), blockTexture(BdBlocks.ACACIA_GLASS_3.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_4.get(), blockTexture(BdBlocks.ACACIA_GLASS_4.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_5.get(), blockTexture(BdBlocks.ACACIA_GLASS_5.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_6.get(), blockTexture(BdBlocks.ACACIA_GLASS_6.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_7.get(), blockTexture(BdBlocks.ACACIA_GLASS_7.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.ACACIA_GLASS_PANE_8.get(), blockTexture(BdBlocks.ACACIA_GLASS_8.get()), blockTexture(BdBlocks.ACACIA_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.ACACIA_PLANKS_1.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_2.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_3.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_4.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_5.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_6.get());
        simpleBlock(BdBlocks.ACACIA_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_1.get(), blockTexture(BdBlocks.ACACIA_PLANKS_1.get()), blockTexture(BdBlocks.ACACIA_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_2.get(), blockTexture(BdBlocks.ACACIA_PLANKS_2.get()), blockTexture(BdBlocks.ACACIA_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_3.get(), blockTexture(BdBlocks.ACACIA_PLANKS_3.get()), blockTexture(BdBlocks.ACACIA_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_4.get(), blockTexture(BdBlocks.ACACIA_PLANKS_4.get()), blockTexture(BdBlocks.ACACIA_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_5.get(), blockTexture(BdBlocks.ACACIA_PLANKS_5.get()), blockTexture(BdBlocks.ACACIA_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_6.get(), blockTexture(BdBlocks.ACACIA_PLANKS_6.get()), blockTexture(BdBlocks.ACACIA_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.ACACIA_SLAB_7.get(), blockTexture(BdBlocks.ACACIA_PLANKS_7.get()), blockTexture(BdBlocks.ACACIA_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_1.get(), blockTexture(BdBlocks.ACACIA_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_2.get(), blockTexture(BdBlocks.ACACIA_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_3.get(), blockTexture(BdBlocks.ACACIA_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_4.get(), blockTexture(BdBlocks.ACACIA_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_5.get(), blockTexture(BdBlocks.ACACIA_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_6.get(), blockTexture(BdBlocks.ACACIA_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.ACACIA_STAIRS_7.get(), blockTexture(BdBlocks.ACACIA_PLANKS_7.get()));

        simpleBlock(BdBlocks.BAMBOO_FRAME_1.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_2.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_3.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_4.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_5.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_6.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_7.get());
        simpleBlock(BdBlocks.BAMBOO_FRAME_8.get());
        simpleBlock(BdBlocks.BAMBOO_GLASS_1.get());
        topSideBlock(BdBlocks.BAMBOO_GLASS_2.get(), blockTexture(BdBlocks.BAMBOO_GLASS_2.get()), blockTexture(BdBlocks.BAMBOO_GLASS_2.get()));
        topSideBlock(BdBlocks.BAMBOO_GLASS_3.get(), blockTexture(BdBlocks.BAMBOO_GLASS_3.get()), blockTexture(BdBlocks.BAMBOO_GLASS_3.get()));
        simpleBlock(BdBlocks.BAMBOO_GLASS_4.get());
        topSideBlock(BdBlocks.BAMBOO_GLASS_5.get(), blockTexture(BdBlocks.BAMBOO_GLASS_5.get()), blockTexture(BdBlocks.BAMBOO_GLASS_5.get()));
        topSideBlock(BdBlocks.BAMBOO_GLASS_6.get(), blockTexture(BdBlocks.BAMBOO_GLASS_6.get()), blockTexture(BdBlocks.BAMBOO_GLASS_6.get()));
        topSideBlock(BdBlocks.BAMBOO_GLASS_7.get(), blockTexture(BdBlocks.BAMBOO_GLASS_7.get()), blockTexture(BdBlocks.BAMBOO_GLASS_7.get()));
        simpleBlock(BdBlocks.BAMBOO_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_1.get(), blockTexture(BdBlocks.BAMBOO_GLASS_1.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_2.get(), blockTexture(BdBlocks.BAMBOO_GLASS_2.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_3.get(), blockTexture(BdBlocks.BAMBOO_GLASS_3.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_4.get(), blockTexture(BdBlocks.BAMBOO_GLASS_4.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_5.get(), blockTexture(BdBlocks.BAMBOO_GLASS_5.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_6.get(), blockTexture(BdBlocks.BAMBOO_GLASS_6.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_7.get(), blockTexture(BdBlocks.BAMBOO_GLASS_7.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BAMBOO_GLASS_PANE_8.get(), blockTexture(BdBlocks.BAMBOO_GLASS_8.get()), blockTexture(BdBlocks.BAMBOO_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.BAMBOO_PLANKS_1.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_2.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_3.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_4.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_5.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_6.get());
        simpleBlock(BdBlocks.BAMBOO_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_1.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_1.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_2.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_2.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_3.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_3.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_4.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_4.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_5.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_5.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_6.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_6.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.BAMBOO_SLAB_7.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_7.get()), blockTexture(BdBlocks.BAMBOO_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_1.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_2.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_3.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_4.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_5.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_6.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.BAMBOO_STAIRS_7.get(), blockTexture(BdBlocks.BAMBOO_PLANKS_7.get()));

        simpleBlock(BdBlocks.BIRCH_FRAME_1.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_2.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_3.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_4.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_5.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_6.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_7.get());
        simpleBlock(BdBlocks.BIRCH_FRAME_8.get());
        simpleBlock(BdBlocks.BIRCH_GLASS_1.get());
        topSideBlock(BdBlocks.BIRCH_GLASS_2.get(), blockTexture(BdBlocks.BIRCH_GLASS_2.get()), blockTexture(BdBlocks.BIRCH_GLASS_2.get()));
        topSideBlock(BdBlocks.BIRCH_GLASS_3.get(), blockTexture(BdBlocks.BIRCH_GLASS_3.get()), blockTexture(BdBlocks.BIRCH_GLASS_3.get()));
        simpleBlock(BdBlocks.BIRCH_GLASS_4.get());
        topSideBlock(BdBlocks.BIRCH_GLASS_5.get(), blockTexture(BdBlocks.BIRCH_GLASS_5.get()), blockTexture(BdBlocks.BIRCH_GLASS_5.get()));
        topSideBlock(BdBlocks.BIRCH_GLASS_6.get(), blockTexture(BdBlocks.BIRCH_GLASS_6.get()), blockTexture(BdBlocks.BIRCH_GLASS_6.get()));
        topSideBlock(BdBlocks.BIRCH_GLASS_7.get(), blockTexture(BdBlocks.BIRCH_GLASS_7.get()), blockTexture(BdBlocks.BIRCH_GLASS_7.get()));
        simpleBlock(BdBlocks.BIRCH_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_1.get(), blockTexture(BdBlocks.BIRCH_GLASS_1.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_2.get(), blockTexture(BdBlocks.BIRCH_GLASS_2.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_3.get(), blockTexture(BdBlocks.BIRCH_GLASS_3.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_4.get(), blockTexture(BdBlocks.BIRCH_GLASS_4.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_5.get(), blockTexture(BdBlocks.BIRCH_GLASS_5.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_6.get(), blockTexture(BdBlocks.BIRCH_GLASS_6.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_7.get(), blockTexture(BdBlocks.BIRCH_GLASS_7.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.BIRCH_GLASS_PANE_8.get(), blockTexture(BdBlocks.BIRCH_GLASS_8.get()), blockTexture(BdBlocks.BIRCH_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.BIRCH_PLANKS_1.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_2.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_3.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_4.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_5.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_6.get());
        simpleBlock(BdBlocks.BIRCH_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_1.get(), blockTexture(BdBlocks.BIRCH_PLANKS_1.get()), blockTexture(BdBlocks.BIRCH_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_2.get(), blockTexture(BdBlocks.BIRCH_PLANKS_2.get()), blockTexture(BdBlocks.BIRCH_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_3.get(), blockTexture(BdBlocks.BIRCH_PLANKS_3.get()), blockTexture(BdBlocks.BIRCH_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_4.get(), blockTexture(BdBlocks.BIRCH_PLANKS_4.get()), blockTexture(BdBlocks.BIRCH_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_5.get(), blockTexture(BdBlocks.BIRCH_PLANKS_5.get()), blockTexture(BdBlocks.BIRCH_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_6.get(), blockTexture(BdBlocks.BIRCH_PLANKS_6.get()), blockTexture(BdBlocks.BIRCH_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.BIRCH_SLAB_7.get(), blockTexture(BdBlocks.BIRCH_PLANKS_7.get()), blockTexture(BdBlocks.BIRCH_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_1.get(), blockTexture(BdBlocks.BIRCH_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_2.get(), blockTexture(BdBlocks.BIRCH_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_3.get(), blockTexture(BdBlocks.BIRCH_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_4.get(), blockTexture(BdBlocks.BIRCH_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_5.get(), blockTexture(BdBlocks.BIRCH_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_6.get(), blockTexture(BdBlocks.BIRCH_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.BIRCH_STAIRS_7.get(), blockTexture(BdBlocks.BIRCH_PLANKS_7.get()));

        simpleBlock(BdBlocks.CHERRY_FRAME_1.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_2.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_3.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_4.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_5.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_6.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_7.get());
        simpleBlock(BdBlocks.CHERRY_FRAME_8.get());
        simpleBlock(BdBlocks.CHERRY_GLASS_1.get());
        topSideBlock(BdBlocks.CHERRY_GLASS_2.get(), blockTexture(BdBlocks.CHERRY_GLASS_2.get()), blockTexture(BdBlocks.CHERRY_GLASS_2.get()));
        topSideBlock(BdBlocks.CHERRY_GLASS_3.get(), blockTexture(BdBlocks.CHERRY_GLASS_3.get()), blockTexture(BdBlocks.CHERRY_GLASS_3.get()));
        simpleBlock(BdBlocks.CHERRY_GLASS_4.get());
        topSideBlock(BdBlocks.CHERRY_GLASS_5.get(), blockTexture(BdBlocks.CHERRY_GLASS_5.get()), blockTexture(BdBlocks.CHERRY_GLASS_5.get()));
        topSideBlock(BdBlocks.CHERRY_GLASS_6.get(), blockTexture(BdBlocks.CHERRY_GLASS_6.get()), blockTexture(BdBlocks.CHERRY_GLASS_6.get()));
        topSideBlock(BdBlocks.CHERRY_GLASS_7.get(), blockTexture(BdBlocks.CHERRY_GLASS_7.get()), blockTexture(BdBlocks.CHERRY_GLASS_7.get()));
        simpleBlock(BdBlocks.CHERRY_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_1.get(), blockTexture(BdBlocks.CHERRY_GLASS_1.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_2.get(), blockTexture(BdBlocks.CHERRY_GLASS_2.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_3.get(), blockTexture(BdBlocks.CHERRY_GLASS_3.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_4.get(), blockTexture(BdBlocks.CHERRY_GLASS_4.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_5.get(), blockTexture(BdBlocks.CHERRY_GLASS_5.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_6.get(), blockTexture(BdBlocks.CHERRY_GLASS_6.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_7.get(), blockTexture(BdBlocks.CHERRY_GLASS_7.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CHERRY_GLASS_PANE_8.get(), blockTexture(BdBlocks.CHERRY_GLASS_8.get()), blockTexture(BdBlocks.CHERRY_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.CHERRY_PLANKS_1.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_2.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_3.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_4.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_5.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_6.get());
        simpleBlock(BdBlocks.CHERRY_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_1.get(), blockTexture(BdBlocks.CHERRY_PLANKS_1.get()), blockTexture(BdBlocks.CHERRY_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_2.get(), blockTexture(BdBlocks.CHERRY_PLANKS_2.get()), blockTexture(BdBlocks.CHERRY_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_3.get(), blockTexture(BdBlocks.CHERRY_PLANKS_3.get()), blockTexture(BdBlocks.CHERRY_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_4.get(), blockTexture(BdBlocks.CHERRY_PLANKS_4.get()), blockTexture(BdBlocks.CHERRY_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_5.get(), blockTexture(BdBlocks.CHERRY_PLANKS_5.get()), blockTexture(BdBlocks.CHERRY_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_6.get(), blockTexture(BdBlocks.CHERRY_PLANKS_6.get()), blockTexture(BdBlocks.CHERRY_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.CHERRY_SLAB_7.get(), blockTexture(BdBlocks.CHERRY_PLANKS_7.get()), blockTexture(BdBlocks.CHERRY_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_1.get(), blockTexture(BdBlocks.CHERRY_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_2.get(), blockTexture(BdBlocks.CHERRY_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_3.get(), blockTexture(BdBlocks.CHERRY_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_4.get(), blockTexture(BdBlocks.CHERRY_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_5.get(), blockTexture(BdBlocks.CHERRY_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_6.get(), blockTexture(BdBlocks.CHERRY_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.CHERRY_STAIRS_7.get(), blockTexture(BdBlocks.CHERRY_PLANKS_7.get()));

        simpleBlock(BdBlocks.CRIMSON_FRAME_1.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_2.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_3.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_4.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_5.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_6.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_7.get());
        simpleBlock(BdBlocks.CRIMSON_FRAME_8.get());
        simpleBlock(BdBlocks.CRIMSON_GLASS_1.get());
        topSideBlock(BdBlocks.CRIMSON_GLASS_2.get(), blockTexture(BdBlocks.CRIMSON_GLASS_2.get()), blockTexture(BdBlocks.CRIMSON_GLASS_2.get()));
        topSideBlock(BdBlocks.CRIMSON_GLASS_3.get(), blockTexture(BdBlocks.CRIMSON_GLASS_3.get()), blockTexture(BdBlocks.CRIMSON_GLASS_3.get()));
        simpleBlock(BdBlocks.CRIMSON_GLASS_4.get());
        topSideBlock(BdBlocks.CRIMSON_GLASS_5.get(), blockTexture(BdBlocks.CRIMSON_GLASS_5.get()), blockTexture(BdBlocks.CRIMSON_GLASS_5.get()));
        topSideBlock(BdBlocks.CRIMSON_GLASS_6.get(), blockTexture(BdBlocks.CRIMSON_GLASS_6.get()), blockTexture(BdBlocks.CRIMSON_GLASS_6.get()));
        topSideBlock(BdBlocks.CRIMSON_GLASS_7.get(), blockTexture(BdBlocks.CRIMSON_GLASS_7.get()), blockTexture(BdBlocks.CRIMSON_GLASS_7.get()));
        simpleBlock(BdBlocks.CRIMSON_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_1.get(), blockTexture(BdBlocks.CRIMSON_GLASS_1.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_2.get(), blockTexture(BdBlocks.CRIMSON_GLASS_2.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_3.get(), blockTexture(BdBlocks.CRIMSON_GLASS_3.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_4.get(), blockTexture(BdBlocks.CRIMSON_GLASS_4.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_5.get(), blockTexture(BdBlocks.CRIMSON_GLASS_5.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_6.get(), blockTexture(BdBlocks.CRIMSON_GLASS_6.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_7.get(), blockTexture(BdBlocks.CRIMSON_GLASS_7.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.CRIMSON_GLASS_PANE_8.get(), blockTexture(BdBlocks.CRIMSON_GLASS_8.get()), blockTexture(BdBlocks.CRIMSON_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.CRIMSON_PLANKS_1.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_2.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_3.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_4.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_5.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_6.get());
        simpleBlock(BdBlocks.CRIMSON_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_1.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_1.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_2.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_2.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_3.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_3.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_4.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_4.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_5.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_5.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_6.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_6.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.CRIMSON_SLAB_7.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_7.get()), blockTexture(BdBlocks.CRIMSON_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_1.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_2.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_3.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_4.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_5.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_6.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.CRIMSON_STAIRS_7.get(), blockTexture(BdBlocks.CRIMSON_PLANKS_7.get()));

        simpleBlock(BdBlocks.DARK_OAK_FRAME_1.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_2.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_3.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_4.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_5.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_6.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_7.get());
        simpleBlock(BdBlocks.DARK_OAK_FRAME_8.get());
        simpleBlock(BdBlocks.DARK_OAK_GLASS_1.get());
        topSideBlock(BdBlocks.DARK_OAK_GLASS_2.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_2.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_2.get()));
        topSideBlock(BdBlocks.DARK_OAK_GLASS_3.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_3.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_3.get()));
        simpleBlock(BdBlocks.DARK_OAK_GLASS_4.get());
        topSideBlock(BdBlocks.DARK_OAK_GLASS_5.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_5.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_5.get()));
        topSideBlock(BdBlocks.DARK_OAK_GLASS_6.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_6.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_6.get()));
        topSideBlock(BdBlocks.DARK_OAK_GLASS_7.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_7.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_7.get()));
        simpleBlock(BdBlocks.DARK_OAK_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_1.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_1.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_2.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_2.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_3.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_3.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_4.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_4.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_5.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_5.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_6.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_6.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_7.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_7.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.DARK_OAK_GLASS_PANE_8.get(), blockTexture(BdBlocks.DARK_OAK_GLASS_8.get()), blockTexture(BdBlocks.DARK_OAK_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_1.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_2.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_3.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_4.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_5.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_6.get());
        simpleBlock(BdBlocks.DARK_OAK_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_1.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_1.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_2.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_2.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_3.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_3.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_4.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_4.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_5.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_5.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_6.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_6.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.DARK_OAK_SLAB_7.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_7.get()), blockTexture(BdBlocks.DARK_OAK_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_1.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_2.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_3.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_4.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_5.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_6.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.DARK_OAK_STAIRS_7.get(), blockTexture(BdBlocks.DARK_OAK_PLANKS_7.get()));

        simpleBlock(BdBlocks.JUNGLE_FRAME_1.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_2.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_3.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_4.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_5.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_6.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_7.get());
        simpleBlock(BdBlocks.JUNGLE_FRAME_8.get());
        simpleBlock(BdBlocks.JUNGLE_GLASS_1.get());
        topSideBlock(BdBlocks.JUNGLE_GLASS_2.get(), blockTexture(BdBlocks.JUNGLE_GLASS_2.get()), blockTexture(BdBlocks.JUNGLE_GLASS_2.get()));
        topSideBlock(BdBlocks.JUNGLE_GLASS_3.get(), blockTexture(BdBlocks.JUNGLE_GLASS_3.get()), blockTexture(BdBlocks.JUNGLE_GLASS_3.get()));
        simpleBlock(BdBlocks.JUNGLE_GLASS_4.get());
        topSideBlock(BdBlocks.JUNGLE_GLASS_5.get(), blockTexture(BdBlocks.JUNGLE_GLASS_5.get()), blockTexture(BdBlocks.JUNGLE_GLASS_5.get()));
        topSideBlock(BdBlocks.JUNGLE_GLASS_6.get(), blockTexture(BdBlocks.JUNGLE_GLASS_6.get()), blockTexture(BdBlocks.JUNGLE_GLASS_6.get()));
        topSideBlock(BdBlocks.JUNGLE_GLASS_7.get(), blockTexture(BdBlocks.JUNGLE_GLASS_7.get()), blockTexture(BdBlocks.JUNGLE_GLASS_7.get()));
        simpleBlock(BdBlocks.JUNGLE_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_1.get(), blockTexture(BdBlocks.JUNGLE_GLASS_1.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_2.get(), blockTexture(BdBlocks.JUNGLE_GLASS_2.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_3.get(), blockTexture(BdBlocks.JUNGLE_GLASS_3.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_4.get(), blockTexture(BdBlocks.JUNGLE_GLASS_4.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_5.get(), blockTexture(BdBlocks.JUNGLE_GLASS_5.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_6.get(), blockTexture(BdBlocks.JUNGLE_GLASS_6.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_7.get(), blockTexture(BdBlocks.JUNGLE_GLASS_7.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.JUNGLE_GLASS_PANE_8.get(), blockTexture(BdBlocks.JUNGLE_GLASS_8.get()), blockTexture(BdBlocks.JUNGLE_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.JUNGLE_PLANKS_1.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_2.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_3.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_4.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_5.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_6.get());
        simpleBlock(BdBlocks.JUNGLE_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_1.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_1.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_2.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_2.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_3.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_3.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_4.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_4.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_5.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_5.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_6.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_6.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.JUNGLE_SLAB_7.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_7.get()), blockTexture(BdBlocks.JUNGLE_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_1.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_2.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_3.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_4.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_5.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_6.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.JUNGLE_STAIRS_7.get(), blockTexture(BdBlocks.JUNGLE_PLANKS_7.get()));

        simpleBlock(BdBlocks.MANGROVE_FRAME_1.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_2.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_3.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_4.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_5.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_6.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_7.get());
        simpleBlock(BdBlocks.MANGROVE_FRAME_8.get());
        simpleBlock(BdBlocks.MANGROVE_GLASS_1.get());
        topSideBlock(BdBlocks.MANGROVE_GLASS_2.get(), blockTexture(BdBlocks.MANGROVE_GLASS_2.get()), blockTexture(BdBlocks.MANGROVE_GLASS_2.get()));
        topSideBlock(BdBlocks.MANGROVE_GLASS_3.get(), blockTexture(BdBlocks.MANGROVE_GLASS_3.get()), blockTexture(BdBlocks.MANGROVE_GLASS_3.get()));
        simpleBlock(BdBlocks.MANGROVE_GLASS_4.get());
        topSideBlock(BdBlocks.MANGROVE_GLASS_5.get(), blockTexture(BdBlocks.MANGROVE_GLASS_5.get()), blockTexture(BdBlocks.MANGROVE_GLASS_5.get()));
        topSideBlock(BdBlocks.MANGROVE_GLASS_6.get(), blockTexture(BdBlocks.MANGROVE_GLASS_6.get()), blockTexture(BdBlocks.MANGROVE_GLASS_6.get()));
        topSideBlock(BdBlocks.MANGROVE_GLASS_7.get(), blockTexture(BdBlocks.MANGROVE_GLASS_7.get()), blockTexture(BdBlocks.MANGROVE_GLASS_7.get()));
        simpleBlock(BdBlocks.MANGROVE_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_1.get(), blockTexture(BdBlocks.MANGROVE_GLASS_1.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_2.get(), blockTexture(BdBlocks.MANGROVE_GLASS_2.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_3.get(), blockTexture(BdBlocks.MANGROVE_GLASS_3.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_4.get(), blockTexture(BdBlocks.MANGROVE_GLASS_4.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_5.get(), blockTexture(BdBlocks.MANGROVE_GLASS_5.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_6.get(), blockTexture(BdBlocks.MANGROVE_GLASS_6.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_7.get(), blockTexture(BdBlocks.MANGROVE_GLASS_7.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.MANGROVE_GLASS_PANE_8.get(), blockTexture(BdBlocks.MANGROVE_GLASS_8.get()), blockTexture(BdBlocks.MANGROVE_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.MANGROVE_PLANKS_1.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_2.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_3.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_4.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_5.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_6.get());
        simpleBlock(BdBlocks.MANGROVE_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_1.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_1.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_2.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_2.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_3.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_3.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_4.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_4.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_5.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_5.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_6.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_6.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.MANGROVE_SLAB_7.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_7.get()), blockTexture(BdBlocks.MANGROVE_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_1.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_2.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_3.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_4.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_5.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_6.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.MANGROVE_STAIRS_7.get(), blockTexture(BdBlocks.MANGROVE_PLANKS_7.get()));

        simpleBlock(BdBlocks.OAK_FRAME_1.get());
        simpleBlock(BdBlocks.OAK_FRAME_2.get());
        simpleBlock(BdBlocks.OAK_FRAME_3.get());
        simpleBlock(BdBlocks.OAK_FRAME_4.get());
        simpleBlock(BdBlocks.OAK_FRAME_5.get());
        simpleBlock(BdBlocks.OAK_FRAME_6.get());
        simpleBlock(BdBlocks.OAK_FRAME_7.get());
        simpleBlock(BdBlocks.OAK_FRAME_8.get());
        simpleBlock(BdBlocks.OAK_GLASS_1.get());
        topSideBlock(BdBlocks.OAK_GLASS_2.get(), blockTexture(BdBlocks.OAK_GLASS_2.get()), blockTexture(BdBlocks.OAK_GLASS_2.get()));
        topSideBlock(BdBlocks.OAK_GLASS_3.get(), blockTexture(BdBlocks.OAK_GLASS_3.get()), blockTexture(BdBlocks.OAK_GLASS_3.get()));
        simpleBlock(BdBlocks.OAK_GLASS_4.get());
        topSideBlock(BdBlocks.OAK_GLASS_5.get(), blockTexture(BdBlocks.OAK_GLASS_5.get()), blockTexture(BdBlocks.OAK_GLASS_5.get()));
        topSideBlock(BdBlocks.OAK_GLASS_6.get(), blockTexture(BdBlocks.OAK_GLASS_6.get()), blockTexture(BdBlocks.OAK_GLASS_6.get()));
        topSideBlock(BdBlocks.OAK_GLASS_7.get(), blockTexture(BdBlocks.OAK_GLASS_7.get()), blockTexture(BdBlocks.OAK_GLASS_7.get()));
        simpleBlock(BdBlocks.OAK_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_1.get(), blockTexture(BdBlocks.OAK_GLASS_1.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_2.get(), blockTexture(BdBlocks.OAK_GLASS_2.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_3.get(), blockTexture(BdBlocks.OAK_GLASS_3.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_4.get(), blockTexture(BdBlocks.OAK_GLASS_4.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_5.get(), blockTexture(BdBlocks.OAK_GLASS_5.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_6.get(), blockTexture(BdBlocks.OAK_GLASS_6.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_7.get(), blockTexture(BdBlocks.OAK_GLASS_7.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.OAK_GLASS_PANE_8.get(), blockTexture(BdBlocks.OAK_GLASS_8.get()), blockTexture(BdBlocks.OAK_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.OAK_PLANKS_1.get());
        simpleBlock(BdBlocks.OAK_PLANKS_2.get());
        simpleBlock(BdBlocks.OAK_PLANKS_3.get());
        simpleBlock(BdBlocks.OAK_PLANKS_4.get());
        simpleBlock(BdBlocks.OAK_PLANKS_5.get());
        simpleBlock(BdBlocks.OAK_PLANKS_6.get());
        simpleBlock(BdBlocks.OAK_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_1.get(), blockTexture(BdBlocks.OAK_PLANKS_1.get()), blockTexture(BdBlocks.OAK_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_2.get(), blockTexture(BdBlocks.OAK_PLANKS_2.get()), blockTexture(BdBlocks.OAK_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_3.get(), blockTexture(BdBlocks.OAK_PLANKS_3.get()), blockTexture(BdBlocks.OAK_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_4.get(), blockTexture(BdBlocks.OAK_PLANKS_4.get()), blockTexture(BdBlocks.OAK_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_5.get(), blockTexture(BdBlocks.OAK_PLANKS_5.get()), blockTexture(BdBlocks.OAK_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_6.get(), blockTexture(BdBlocks.OAK_PLANKS_6.get()), blockTexture(BdBlocks.OAK_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.OAK_SLAB_7.get(), blockTexture(BdBlocks.OAK_PLANKS_7.get()), blockTexture(BdBlocks.OAK_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_1.get(), blockTexture(BdBlocks.OAK_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_2.get(), blockTexture(BdBlocks.OAK_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_3.get(), blockTexture(BdBlocks.OAK_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_4.get(), blockTexture(BdBlocks.OAK_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_5.get(), blockTexture(BdBlocks.OAK_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_6.get(), blockTexture(BdBlocks.OAK_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.OAK_STAIRS_7.get(), blockTexture(BdBlocks.OAK_PLANKS_7.get()));

        simpleBlock(BdBlocks.SPRUCE_FRAME_1.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_2.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_3.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_4.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_5.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_6.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_7.get());
        simpleBlock(BdBlocks.SPRUCE_FRAME_8.get());
        simpleBlock(BdBlocks.SPRUCE_GLASS_1.get());
        topSideBlock(BdBlocks.SPRUCE_GLASS_2.get(), blockTexture(BdBlocks.SPRUCE_GLASS_2.get()), blockTexture(BdBlocks.SPRUCE_GLASS_2.get()));
        topSideBlock(BdBlocks.SPRUCE_GLASS_3.get(), blockTexture(BdBlocks.SPRUCE_GLASS_3.get()), blockTexture(BdBlocks.SPRUCE_GLASS_3.get()));
        simpleBlock(BdBlocks.SPRUCE_GLASS_4.get());
        topSideBlock(BdBlocks.SPRUCE_GLASS_5.get(), blockTexture(BdBlocks.SPRUCE_GLASS_5.get()), blockTexture(BdBlocks.SPRUCE_GLASS_5.get()));
        topSideBlock(BdBlocks.SPRUCE_GLASS_6.get(), blockTexture(BdBlocks.SPRUCE_GLASS_6.get()), blockTexture(BdBlocks.SPRUCE_GLASS_6.get()));
        topSideBlock(BdBlocks.SPRUCE_GLASS_7.get(), blockTexture(BdBlocks.SPRUCE_GLASS_7.get()), blockTexture(BdBlocks.SPRUCE_GLASS_7.get()));
        simpleBlock(BdBlocks.SPRUCE_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_1.get(), blockTexture(BdBlocks.SPRUCE_GLASS_1.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_2.get(), blockTexture(BdBlocks.SPRUCE_GLASS_2.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_3.get(), blockTexture(BdBlocks.SPRUCE_GLASS_3.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_4.get(), blockTexture(BdBlocks.SPRUCE_GLASS_4.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_5.get(), blockTexture(BdBlocks.SPRUCE_GLASS_5.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_6.get(), blockTexture(BdBlocks.SPRUCE_GLASS_6.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_7.get(), blockTexture(BdBlocks.SPRUCE_GLASS_7.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.SPRUCE_GLASS_PANE_8.get(), blockTexture(BdBlocks.SPRUCE_GLASS_8.get()), blockTexture(BdBlocks.SPRUCE_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.SPRUCE_PLANKS_1.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_2.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_3.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_4.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_5.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_6.get());
        simpleBlock(BdBlocks.SPRUCE_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_1.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_1.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_2.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_2.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_3.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_3.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_4.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_4.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_5.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_5.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_6.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_6.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.SPRUCE_SLAB_7.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_7.get()), blockTexture(BdBlocks.SPRUCE_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_1.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_2.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_3.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_4.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_5.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_6.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.SPRUCE_STAIRS_7.get(), blockTexture(BdBlocks.SPRUCE_PLANKS_7.get()));

        simpleBlock(BdBlocks.WARPED_FRAME_1.get());
        simpleBlock(BdBlocks.WARPED_FRAME_2.get());
        simpleBlock(BdBlocks.WARPED_FRAME_3.get());
        simpleBlock(BdBlocks.WARPED_FRAME_4.get());
        simpleBlock(BdBlocks.WARPED_FRAME_5.get());
        simpleBlock(BdBlocks.WARPED_FRAME_6.get());
        simpleBlock(BdBlocks.WARPED_FRAME_7.get());
        simpleBlock(BdBlocks.WARPED_FRAME_8.get());
        simpleBlock(BdBlocks.WARPED_GLASS_1.get());
        topSideBlock(BdBlocks.WARPED_GLASS_2.get(), blockTexture(BdBlocks.WARPED_GLASS_2.get()), blockTexture(BdBlocks.WARPED_GLASS_2.get()));
        topSideBlock(BdBlocks.WARPED_GLASS_3.get(), blockTexture(BdBlocks.WARPED_GLASS_3.get()), blockTexture(BdBlocks.WARPED_GLASS_3.get()));
        simpleBlock(BdBlocks.WARPED_GLASS_4.get());
        topSideBlock(BdBlocks.WARPED_GLASS_5.get(), blockTexture(BdBlocks.WARPED_GLASS_5.get()), blockTexture(BdBlocks.WARPED_GLASS_5.get()));
        topSideBlock(BdBlocks.WARPED_GLASS_6.get(), blockTexture(BdBlocks.WARPED_GLASS_6.get()), blockTexture(BdBlocks.WARPED_GLASS_6.get()));
        topSideBlock(BdBlocks.WARPED_GLASS_7.get(), blockTexture(BdBlocks.WARPED_GLASS_7.get()), blockTexture(BdBlocks.WARPED_GLASS_7.get()));
        simpleBlock(BdBlocks.WARPED_GLASS_8.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_1.get(), blockTexture(BdBlocks.WARPED_GLASS_1.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_2.get(), blockTexture(BdBlocks.WARPED_GLASS_2.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_3.get(), blockTexture(BdBlocks.WARPED_GLASS_3.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_4.get(), blockTexture(BdBlocks.WARPED_GLASS_4.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_5.get(), blockTexture(BdBlocks.WARPED_GLASS_5.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_6.get(), blockTexture(BdBlocks.WARPED_GLASS_6.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_7.get(), blockTexture(BdBlocks.WARPED_GLASS_7.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_7.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.WARPED_GLASS_PANE_8.get(), blockTexture(BdBlocks.WARPED_GLASS_8.get()), blockTexture(BdBlocks.WARPED_GLASS_PANE_8.get()));
        simpleBlock(BdBlocks.WARPED_PLANKS_1.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_2.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_3.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_4.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_5.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_6.get());
        simpleBlock(BdBlocks.WARPED_PLANKS_7.get());
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_1.get(), blockTexture(BdBlocks.WARPED_PLANKS_1.get()), blockTexture(BdBlocks.WARPED_PLANKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_2.get(), blockTexture(BdBlocks.WARPED_PLANKS_2.get()), blockTexture(BdBlocks.WARPED_PLANKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_3.get(), blockTexture(BdBlocks.WARPED_PLANKS_3.get()), blockTexture(BdBlocks.WARPED_PLANKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_4.get(), blockTexture(BdBlocks.WARPED_PLANKS_4.get()), blockTexture(BdBlocks.WARPED_PLANKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_5.get(), blockTexture(BdBlocks.WARPED_PLANKS_5.get()), blockTexture(BdBlocks.WARPED_PLANKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_6.get(), blockTexture(BdBlocks.WARPED_PLANKS_6.get()), blockTexture(BdBlocks.WARPED_PLANKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.WARPED_SLAB_7.get(), blockTexture(BdBlocks.WARPED_PLANKS_7.get()), blockTexture(BdBlocks.WARPED_PLANKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_1.get(), blockTexture(BdBlocks.WARPED_PLANKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_2.get(), blockTexture(BdBlocks.WARPED_PLANKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_3.get(), blockTexture(BdBlocks.WARPED_PLANKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_4.get(), blockTexture(BdBlocks.WARPED_PLANKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_5.get(), blockTexture(BdBlocks.WARPED_PLANKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_6.get(), blockTexture(BdBlocks.WARPED_PLANKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.WARPED_STAIRS_7.get(), blockTexture(BdBlocks.WARPED_PLANKS_7.get()));

        simpleBlock(BdBlocks.GLASS_1.get());
        simpleBlock(BdBlocks.GLASS_2.get());
        simpleBlock(BdBlocks.GLASS_3.get());
        simpleBlock(BdBlocks.GLASS_4.get());
        simpleBlock(BdBlocks.GLASS_5.get());
        simpleBlock(BdBlocks.GLASS_6.get());
        simpleBlock(BdBlocks.GLASS_7.get());
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_1.get(), blockTexture(BdBlocks.GLASS_1.get()), blockTexture(BdBlocks.GLASS_PANE_1.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_2.get(), blockTexture(BdBlocks.GLASS_2.get()), blockTexture(BdBlocks.GLASS_PANE_2.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_3.get(), blockTexture(BdBlocks.GLASS_3.get()), blockTexture(BdBlocks.GLASS_PANE_3.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_4.get(), blockTexture(BdBlocks.GLASS_4.get()), blockTexture(BdBlocks.GLASS_PANE_4.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_5.get(), blockTexture(BdBlocks.GLASS_5.get()), blockTexture(BdBlocks.GLASS_PANE_5.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_6.get(), blockTexture(BdBlocks.GLASS_6.get()), blockTexture(BdBlocks.GLASS_PANE_6.get()));
        bdPaneBlock((IronBarsBlock) BdBlocks.GLASS_PANE_7.get(), blockTexture(BdBlocks.GLASS_7.get()), blockTexture(BdBlocks.GLASS_PANE_7.get()));

        logBlock((RotatedPillarBlock) BdBlocks.ANDESITE_1.get());
        simpleBlock(BdBlocks.ANDESITE_2.get());
        simpleBlock(BdBlocks.ANDESITE_3.get());
        simpleBlock(BdBlocks.ANDESITE_4.get());
        simpleBlock(BdBlocks.ANDESITE_5.get());
        simpleBlock(BdBlocks.ANDESITE_6.get());
        simpleBlock(BdBlocks.ANDESITE_7.get());
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_1.get(), blockTexture(BdBlocks.ANDESITE_1.get()), blockTexture(BdBlocks.ANDESITE_1.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_2.get(), blockTexture(BdBlocks.ANDESITE_2.get()), blockTexture(BdBlocks.ANDESITE_2.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_3.get(), blockTexture(BdBlocks.ANDESITE_3.get()), blockTexture(BdBlocks.ANDESITE_3.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_4.get(), blockTexture(BdBlocks.ANDESITE_4.get()), blockTexture(BdBlocks.ANDESITE_4.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_5.get(), blockTexture(BdBlocks.ANDESITE_5.get()), blockTexture(BdBlocks.ANDESITE_5.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_6.get(), blockTexture(BdBlocks.ANDESITE_6.get()), blockTexture(BdBlocks.ANDESITE_6.get()));
        slabBlock((SlabBlock) BdBlocks.ANDESITE_SLAB_7.get(), blockTexture(BdBlocks.ANDESITE_7.get()), blockTexture(BdBlocks.ANDESITE_7.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_1.get(), blockTexture(BdBlocks.ANDESITE_1.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_2.get(), blockTexture(BdBlocks.ANDESITE_2.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_3.get(), blockTexture(BdBlocks.ANDESITE_3.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_4.get(), blockTexture(BdBlocks.ANDESITE_4.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_5.get(), blockTexture(BdBlocks.ANDESITE_5.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_6.get(), blockTexture(BdBlocks.ANDESITE_6.get()));
        stairsBlock((StairBlock) BdBlocks.ANDESITE_STAIRS_7.get(), blockTexture(BdBlocks.ANDESITE_7.get()));

        logBlock((RotatedPillarBlock) BdBlocks.COBBLESTONE_1.get());
        simpleBlock(BdBlocks.COBBLESTONE_2.get());
        simpleBlock(BdBlocks.COBBLESTONE_3.get());
        simpleBlock(BdBlocks.COBBLESTONE_4.get());
        simpleBlock(BdBlocks.COBBLESTONE_5.get());
        simpleBlock(BdBlocks.COBBLESTONE_6.get());
        simpleBlock(BdBlocks.COBBLESTONE_7.get());
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_1.get(), blockTexture(BdBlocks.COBBLESTONE_1.get()), blockTexture(BdBlocks.COBBLESTONE_1.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_2.get(), blockTexture(BdBlocks.COBBLESTONE_2.get()), blockTexture(BdBlocks.COBBLESTONE_2.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_3.get(), blockTexture(BdBlocks.COBBLESTONE_3.get()), blockTexture(BdBlocks.COBBLESTONE_3.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_4.get(), blockTexture(BdBlocks.COBBLESTONE_4.get()), blockTexture(BdBlocks.COBBLESTONE_4.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_5.get(), blockTexture(BdBlocks.COBBLESTONE_5.get()), blockTexture(BdBlocks.COBBLESTONE_5.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_6.get(), blockTexture(BdBlocks.COBBLESTONE_6.get()), blockTexture(BdBlocks.COBBLESTONE_6.get()));
        slabBlock((SlabBlock) BdBlocks.COBBLESTONE_SLAB_7.get(), blockTexture(BdBlocks.COBBLESTONE_7.get()), blockTexture(BdBlocks.COBBLESTONE_7.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_1.get(), blockTexture(BdBlocks.COBBLESTONE_1.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_2.get(), blockTexture(BdBlocks.COBBLESTONE_2.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_3.get(), blockTexture(BdBlocks.COBBLESTONE_3.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_4.get(), blockTexture(BdBlocks.COBBLESTONE_4.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_5.get(), blockTexture(BdBlocks.COBBLESTONE_5.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_6.get(), blockTexture(BdBlocks.COBBLESTONE_6.get()));
        stairsBlock((StairBlock) BdBlocks.COBBLESTONE_STAIRS_7.get(), blockTexture(BdBlocks.COBBLESTONE_7.get()));

        logBlock((RotatedPillarBlock) BdBlocks.DIORITE_1.get());
        simpleBlock(BdBlocks.DIORITE_2.get());
        simpleBlock(BdBlocks.DIORITE_3.get());
        simpleBlock(BdBlocks.DIORITE_4.get());
        simpleBlock(BdBlocks.DIORITE_5.get());
        simpleBlock(BdBlocks.DIORITE_6.get());
        simpleBlock(BdBlocks.DIORITE_7.get());
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_1.get(), blockTexture(BdBlocks.DIORITE_1.get()), blockTexture(BdBlocks.DIORITE_1.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_2.get(), blockTexture(BdBlocks.DIORITE_2.get()), blockTexture(BdBlocks.DIORITE_2.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_3.get(), blockTexture(BdBlocks.DIORITE_3.get()), blockTexture(BdBlocks.DIORITE_3.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_4.get(), blockTexture(BdBlocks.DIORITE_4.get()), blockTexture(BdBlocks.DIORITE_4.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_5.get(), blockTexture(BdBlocks.DIORITE_5.get()), blockTexture(BdBlocks.DIORITE_5.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_6.get(), blockTexture(BdBlocks.DIORITE_6.get()), blockTexture(BdBlocks.DIORITE_6.get()));
        slabBlock((SlabBlock) BdBlocks.DIORITE_SLAB_7.get(), blockTexture(BdBlocks.DIORITE_7.get()), blockTexture(BdBlocks.DIORITE_7.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_1.get(), blockTexture(BdBlocks.DIORITE_1.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_2.get(), blockTexture(BdBlocks.DIORITE_2.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_3.get(), blockTexture(BdBlocks.DIORITE_3.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_4.get(), blockTexture(BdBlocks.DIORITE_4.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_5.get(), blockTexture(BdBlocks.DIORITE_5.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_6.get(), blockTexture(BdBlocks.DIORITE_6.get()));
        stairsBlock((StairBlock) BdBlocks.DIORITE_STAIRS_7.get(), blockTexture(BdBlocks.DIORITE_7.get()));

        logBlock((RotatedPillarBlock) BdBlocks.GRANITE_1.get());
        simpleBlock(BdBlocks.GRANITE_2.get());
        simpleBlock(BdBlocks.GRANITE_3.get());
        simpleBlock(BdBlocks.GRANITE_4.get());
        simpleBlock(BdBlocks.GRANITE_5.get());
        simpleBlock(BdBlocks.GRANITE_6.get());
        simpleBlock(BdBlocks.GRANITE_7.get());
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_1.get(), blockTexture(BdBlocks.GRANITE_1.get()), blockTexture(BdBlocks.GRANITE_1.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_2.get(), blockTexture(BdBlocks.GRANITE_2.get()), blockTexture(BdBlocks.GRANITE_2.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_3.get(), blockTexture(BdBlocks.GRANITE_3.get()), blockTexture(BdBlocks.GRANITE_3.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_4.get(), blockTexture(BdBlocks.GRANITE_4.get()), blockTexture(BdBlocks.GRANITE_4.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_5.get(), blockTexture(BdBlocks.GRANITE_5.get()), blockTexture(BdBlocks.GRANITE_5.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_6.get(), blockTexture(BdBlocks.GRANITE_6.get()), blockTexture(BdBlocks.GRANITE_6.get()));
        slabBlock((SlabBlock) BdBlocks.GRANITE_SLAB_7.get(), blockTexture(BdBlocks.GRANITE_7.get()), blockTexture(BdBlocks.GRANITE_7.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_1.get(), blockTexture(BdBlocks.GRANITE_1.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_2.get(), blockTexture(BdBlocks.GRANITE_2.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_3.get(), blockTexture(BdBlocks.GRANITE_3.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_4.get(), blockTexture(BdBlocks.GRANITE_4.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_5.get(), blockTexture(BdBlocks.GRANITE_5.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_6.get(), blockTexture(BdBlocks.GRANITE_6.get()));
        stairsBlock((StairBlock) BdBlocks.GRANITE_STAIRS_7.get(), blockTexture(BdBlocks.GRANITE_7.get()));

        simpleBlock(BdBlocks.STONE_BRICKS_1.get());
        simpleBlock(BdBlocks.STONE_BRICKS_2.get());
        simpleBlock(BdBlocks.STONE_BRICKS_3.get());
        simpleBlock(BdBlocks.STONE_BRICKS_4.get());
        logBlock((RotatedPillarBlock) BdBlocks.STONE_BRICKS_5.get());
        simpleBlock(BdBlocks.STONE_BRICKS_6.get());
        simpleBlock(BdBlocks.STONE_BRICKS_7.get());
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_1.get(), blockTexture(BdBlocks.STONE_BRICKS_1.get()), blockTexture(BdBlocks.STONE_BRICKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_2.get(), blockTexture(BdBlocks.STONE_BRICKS_2.get()), blockTexture(BdBlocks.STONE_BRICKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_3.get(), blockTexture(BdBlocks.STONE_BRICKS_3.get()), blockTexture(BdBlocks.STONE_BRICKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_4.get(), blockTexture(BdBlocks.STONE_BRICKS_4.get()), blockTexture(BdBlocks.STONE_BRICKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_5.get(), blockTexture(BdBlocks.STONE_BRICKS_5.get()), blockTexture(BdBlocks.STONE_BRICKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_6.get(), blockTexture(BdBlocks.STONE_BRICKS_6.get()), blockTexture(BdBlocks.STONE_BRICKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.STONE_BRICK_SLAB_7.get(), blockTexture(BdBlocks.STONE_BRICKS_7.get()), blockTexture(BdBlocks.STONE_BRICKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_1.get(), blockTexture(BdBlocks.STONE_BRICKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_2.get(), blockTexture(BdBlocks.STONE_BRICKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_3.get(), blockTexture(BdBlocks.STONE_BRICKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_4.get(), blockTexture(BdBlocks.STONE_BRICKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_5.get(), blockTexture(BdBlocks.STONE_BRICKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_6.get(), blockTexture(BdBlocks.STONE_BRICKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.STONE_BRICK_STAIRS_7.get(), blockTexture(BdBlocks.STONE_BRICKS_7.get()));

        simpleBlock(BdBlocks.DEEPSLATE_1.get());
        simpleBlock(BdBlocks.DEEPSLATE_2.get());
        simpleBlock(BdBlocks.DEEPSLATE_3.get());
        simpleBlock(BdBlocks.DEEPSLATE_4.get());
        simpleBlock(BdBlocks.DEEPSLATE_5.get());
        slabBlock((SlabBlock) BdBlocks.DEEPSLATE_SLAB_1.get(), blockTexture(BdBlocks.DEEPSLATE_1.get()), blockTexture(BdBlocks.DEEPSLATE_1.get()));
        slabBlock((SlabBlock) BdBlocks.DEEPSLATE_SLAB_2.get(), blockTexture(BdBlocks.DEEPSLATE_2.get()), blockTexture(BdBlocks.DEEPSLATE_2.get()));
        slabBlock((SlabBlock) BdBlocks.DEEPSLATE_SLAB_3.get(), blockTexture(BdBlocks.DEEPSLATE_3.get()), blockTexture(BdBlocks.DEEPSLATE_3.get()));
        slabBlock((SlabBlock) BdBlocks.DEEPSLATE_SLAB_4.get(), blockTexture(BdBlocks.DEEPSLATE_4.get()), blockTexture(BdBlocks.DEEPSLATE_4.get()));
        slabBlock((SlabBlock) BdBlocks.DEEPSLATE_SLAB_5.get(), blockTexture(BdBlocks.DEEPSLATE_5.get()), blockTexture(BdBlocks.DEEPSLATE_5.get()));
        stairsBlock((StairBlock) BdBlocks.DEEPSLATE_STAIRS_1.get(), blockTexture(BdBlocks.DEEPSLATE_1.get()));
        stairsBlock((StairBlock) BdBlocks.DEEPSLATE_STAIRS_2.get(), blockTexture(BdBlocks.DEEPSLATE_2.get()));
        stairsBlock((StairBlock) BdBlocks.DEEPSLATE_STAIRS_3.get(), blockTexture(BdBlocks.DEEPSLATE_3.get()));
        stairsBlock((StairBlock) BdBlocks.DEEPSLATE_STAIRS_4.get(), blockTexture(BdBlocks.DEEPSLATE_4.get()));
        stairsBlock((StairBlock) BdBlocks.DEEPSLATE_STAIRS_5.get(), blockTexture(BdBlocks.DEEPSLATE_5.get()));

        simpleBlock(BdBlocks.BRICKS_1.get());
        simpleBlock(BdBlocks.BRICKS_2.get());
        simpleBlock(BdBlocks.BRICKS_3.get());
        simpleBlock(BdBlocks.BRICKS_4.get());
        simpleBlock(BdBlocks.BRICKS_5.get());
        simpleBlock(BdBlocks.BRICKS_6.get());
        simpleBlock(BdBlocks.BRICKS_7.get());
        simpleBlock(BdBlocks.BRICKS_8.get());
        simpleBlock(BdBlocks.BRICKS_9.get());
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_1.get(), blockTexture(BdBlocks.BRICKS_1.get()), blockTexture(BdBlocks.BRICKS_1.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_2.get(), blockTexture(BdBlocks.BRICKS_2.get()), blockTexture(BdBlocks.BRICKS_2.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_3.get(), blockTexture(BdBlocks.BRICKS_3.get()), blockTexture(BdBlocks.BRICKS_3.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_4.get(), blockTexture(BdBlocks.BRICKS_4.get()), blockTexture(BdBlocks.BRICKS_4.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_5.get(), blockTexture(BdBlocks.BRICKS_5.get()), blockTexture(BdBlocks.BRICKS_5.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_6.get(), blockTexture(BdBlocks.BRICKS_6.get()), blockTexture(BdBlocks.BRICKS_6.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_7.get(), blockTexture(BdBlocks.BRICKS_7.get()), blockTexture(BdBlocks.BRICKS_7.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_8.get(), blockTexture(BdBlocks.BRICKS_8.get()), blockTexture(BdBlocks.BRICKS_8.get()));
        slabBlock((SlabBlock) BdBlocks.BRICK_SLAB_9.get(), blockTexture(BdBlocks.BRICKS_9.get()), blockTexture(BdBlocks.BRICKS_9.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_1.get(), blockTexture(BdBlocks.BRICKS_1.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_2.get(), blockTexture(BdBlocks.BRICKS_2.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_3.get(), blockTexture(BdBlocks.BRICKS_3.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_4.get(), blockTexture(BdBlocks.BRICKS_4.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_5.get(), blockTexture(BdBlocks.BRICKS_5.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_6.get(), blockTexture(BdBlocks.BRICKS_6.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_7.get(), blockTexture(BdBlocks.BRICKS_7.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_8.get(), blockTexture(BdBlocks.BRICKS_8.get()));
        stairsBlock((StairBlock) BdBlocks.BRICK_STAIRS_9.get(), blockTexture(BdBlocks.BRICKS_9.get()));

        simpleBlock(BdBlocks.SANDSTONE_1.get());
        simpleBlock(BdBlocks.SANDSTONE_2.get());
        simpleBlock(BdBlocks.SANDSTONE_3.get());
        simpleBlock(BdBlocks.SANDSTONE_4.get());
        simpleBlock(BdBlocks.SANDSTONE_5.get());
        simpleBlock(BdBlocks.SANDSTONE_6.get());
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_1.get(), blockTexture(BdBlocks.SANDSTONE_1.get()), blockTexture(BdBlocks.SANDSTONE_1.get()));
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_2.get(), blockTexture(BdBlocks.SANDSTONE_2.get()), blockTexture(BdBlocks.SANDSTONE_2.get()));
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_3.get(), blockTexture(BdBlocks.SANDSTONE_3.get()), blockTexture(BdBlocks.SANDSTONE_3.get()));
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_4.get(), blockTexture(BdBlocks.SANDSTONE_4.get()), blockTexture(BdBlocks.SANDSTONE_4.get()));
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_5.get(), blockTexture(BdBlocks.SANDSTONE_5.get()), blockTexture(BdBlocks.SANDSTONE_5.get()));
        slabBlock((SlabBlock) BdBlocks.SANDSTONE_SLAB_6.get(), blockTexture(BdBlocks.SANDSTONE_6.get()), blockTexture(BdBlocks.SANDSTONE_6.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_1.get(), blockTexture(BdBlocks.SANDSTONE_1.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_2.get(), blockTexture(BdBlocks.SANDSTONE_2.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_3.get(), blockTexture(BdBlocks.SANDSTONE_3.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_4.get(), blockTexture(BdBlocks.SANDSTONE_4.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_5.get(), blockTexture(BdBlocks.SANDSTONE_5.get()));
        stairsBlock((StairBlock) BdBlocks.SANDSTONE_STAIRS_6.get(), blockTexture(BdBlocks.SANDSTONE_6.get()));

        simpleBlock(BdBlocks.PRISMARINE_1.get());
        simpleBlock(BdBlocks.PRISMARINE_2.get());
        simpleBlock(BdBlocks.PRISMARINE_3.get());
        simpleBlock(BdBlocks.PRISMARINE_4.get());
        simpleBlock(BdBlocks.PRISMARINE_5.get());
        logBlock((RotatedPillarBlock) BdBlocks.PRISMARINE_6.get());
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_1.get(), blockTexture(BdBlocks.PRISMARINE_1.get()), blockTexture(BdBlocks.PRISMARINE_1.get()));
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_2.get(), blockTexture(BdBlocks.PRISMARINE_2.get()), blockTexture(BdBlocks.PRISMARINE_2.get()));
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_3.get(), blockTexture(BdBlocks.PRISMARINE_3.get()), blockTexture(BdBlocks.PRISMARINE_3.get()));
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_4.get(), blockTexture(BdBlocks.PRISMARINE_4.get()), blockTexture(BdBlocks.PRISMARINE_4.get()));
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_5.get(), blockTexture(BdBlocks.PRISMARINE_5.get()), blockTexture(BdBlocks.PRISMARINE_5.get()));
        slabBlock((SlabBlock) BdBlocks.PRISMARINE_SLAB_6.get(), blockTexture(BdBlocks.PRISMARINE_6.get()), blockTexture(BdBlocks.PRISMARINE_6.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_1.get(), blockTexture(BdBlocks.PRISMARINE_1.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_2.get(), blockTexture(BdBlocks.PRISMARINE_2.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_3.get(), blockTexture(BdBlocks.PRISMARINE_3.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_4.get(), blockTexture(BdBlocks.PRISMARINE_4.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_5.get(), blockTexture(BdBlocks.PRISMARINE_5.get()));
        stairsBlock((StairBlock) BdBlocks.PRISMARINE_STAIRS_6.get(), blockTexture(BdBlocks.PRISMARINE_6.get()));

        simpleBlock(BdBlocks.BLACKSTONE_1.get());
        simpleBlock(BdBlocks.BLACKSTONE_2.get());
        simpleBlock(BdBlocks.BLACKSTONE_3.get());
        simpleBlock(BdBlocks.BLACKSTONE_4.get());
        simpleBlock(BdBlocks.BLACKSTONE_5.get());
        logBlock((RotatedPillarBlock) BdBlocks.BLACKSTONE_6.get());

        simpleBlock(BdBlocks.GILDED_BLACKSTONE_1.get());
        simpleBlock(BdBlocks.GILDED_BLACKSTONE_2.get());
        simpleBlock(BdBlocks.GILDED_BLACKSTONE_3.get());
        logBlock((RotatedPillarBlock) BdBlocks.GILDED_BLACKSTONE_4.get());

        simpleBlock(BdBlocks.NETHER_BRICKS_1.get());
        simpleBlock(BdBlocks.NETHER_BRICKS_2.get());
        simpleBlock(BdBlocks.NETHER_BRICKS_3.get());
        simpleBlock(BdBlocks.NETHER_BRICKS_4.get());
        simpleBlock(BdBlocks.NETHER_BRICKS_5.get());
        logBlock((RotatedPillarBlock) BdBlocks.NETHER_BRICKS_6.get());

        simpleBlock(BdBlocks.GILDED_NETHER_BRICKS_1.get());
        simpleBlock(BdBlocks.GILDED_NETHER_BRICKS_2.get());
        simpleBlock(BdBlocks.GILDED_NETHER_BRICKS_3.get());
        logBlock((RotatedPillarBlock) BdBlocks.GILDED_NETHER_BRICKS_4.get());

        simpleBlock(BdBlocks.CALCITE_1.get());
        simpleBlock(BdBlocks.CALCITE_2.get());
        simpleBlock(BdBlocks.CALCITE_3.get());
        simpleBlock(BdBlocks.CALCITE_4.get());
        simpleBlock(BdBlocks.CALCITE_5.get());
        simpleBlock(BdBlocks.CALCITE_6.get());
        simpleBlock(BdBlocks.CALCITE_7.get());
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_1.get(), blockTexture(BdBlocks.CALCITE_1.get()), blockTexture(BdBlocks.CALCITE_1.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_2.get(), blockTexture(BdBlocks.CALCITE_2.get()), blockTexture(BdBlocks.CALCITE_2.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_3.get(), blockTexture(BdBlocks.CALCITE_3.get()), blockTexture(BdBlocks.CALCITE_3.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_4.get(), blockTexture(BdBlocks.CALCITE_4.get()), blockTexture(BdBlocks.CALCITE_4.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_5.get(), blockTexture(BdBlocks.CALCITE_5.get()), blockTexture(BdBlocks.CALCITE_5.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_6.get(), blockTexture(BdBlocks.CALCITE_6.get()), blockTexture(BdBlocks.CALCITE_6.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_7.get(), blockTexture(BdBlocks.CALCITE_7.get()), blockTexture(BdBlocks.CALCITE_7.get()));
        slabBlock((SlabBlock) BdBlocks.CALCITE_SLAB_8.get(), blockTexture(Blocks.CALCITE), blockTexture(Blocks.CALCITE));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_1.get(), blockTexture(BdBlocks.CALCITE_1.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_2.get(), blockTexture(BdBlocks.CALCITE_2.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_3.get(), blockTexture(BdBlocks.CALCITE_3.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_4.get(), blockTexture(BdBlocks.CALCITE_4.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_5.get(), blockTexture(BdBlocks.CALCITE_5.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_6.get(), blockTexture(BdBlocks.CALCITE_6.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_7.get(), blockTexture(BdBlocks.CALCITE_7.get()));
        stairsBlock((StairBlock) BdBlocks.CALCITE_STAIRS_8.get(), blockTexture(Blocks.CALCITE));

        logBlock((RotatedPillarBlock) BdBlocks.DRIPSTONE_1.get());
        simpleBlock(BdBlocks.DRIPSTONE_2.get());
        simpleBlock(BdBlocks.DRIPSTONE_3.get());
        logBlock((RotatedPillarBlock) BdBlocks.DRIPSTONE_4.get());
        simpleBlock(BdBlocks.DRIPSTONE_5.get());
        simpleBlock(BdBlocks.DRIPSTONE_6.get());
        simpleBlock(BdBlocks.DRIPSTONE_7.get());
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_1.get(), blockTexture(BdBlocks.DRIPSTONE_1.get()), blockTexture(BdBlocks.DRIPSTONE_1.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_2.get(), blockTexture(BdBlocks.DRIPSTONE_2.get()), blockTexture(BdBlocks.DRIPSTONE_2.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_3.get(), blockTexture(BdBlocks.DRIPSTONE_3.get()), blockTexture(BdBlocks.DRIPSTONE_3.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_4.get(), blockTexture(BdBlocks.DRIPSTONE_4.get()), blockTexture(BdBlocks.DRIPSTONE_4.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_5.get(), blockTexture(BdBlocks.DRIPSTONE_5.get()), blockTexture(BdBlocks.DRIPSTONE_5.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_6.get(), blockTexture(BdBlocks.DRIPSTONE_6.get()), blockTexture(BdBlocks.DRIPSTONE_6.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_7.get(), blockTexture(BdBlocks.DRIPSTONE_7.get()), blockTexture(BdBlocks.DRIPSTONE_7.get()));
        slabBlock((SlabBlock) BdBlocks.DRIPSTONE_SLAB_8.get(), blockTexture(Blocks.DRIPSTONE_BLOCK), blockTexture(Blocks.DRIPSTONE_BLOCK));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_1.get(), blockTexture(BdBlocks.DRIPSTONE_1.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_2.get(), blockTexture(BdBlocks.DRIPSTONE_2.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_3.get(), blockTexture(BdBlocks.DRIPSTONE_3.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_4.get(), blockTexture(BdBlocks.DRIPSTONE_4.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_5.get(), blockTexture(BdBlocks.DRIPSTONE_5.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_6.get(), blockTexture(BdBlocks.DRIPSTONE_6.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_7.get(), blockTexture(BdBlocks.DRIPSTONE_7.get()));
        stairsBlock((StairBlock) BdBlocks.DRIPSTONE_STAIRS_8.get(), blockTexture(Blocks.DRIPSTONE_BLOCK));

        logBlock((RotatedPillarBlock) BdBlocks.TUFF_1.get());
        simpleBlock(BdBlocks.TUFF_2.get());
        simpleBlock(BdBlocks.TUFF_3.get());
        simpleBlock(BdBlocks.TUFF_4.get());
        logBlock((RotatedPillarBlock) BdBlocks.TUFF_5.get());
        simpleBlock(BdBlocks.TUFF_6.get());
        simpleBlock(BdBlocks.TUFF_7.get());
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_1.get(), blockTexture(BdBlocks.TUFF_1.get()), blockTexture(BdBlocks.TUFF_1.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_2.get(), blockTexture(BdBlocks.TUFF_2.get()), blockTexture(BdBlocks.TUFF_2.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_3.get(), blockTexture(BdBlocks.TUFF_3.get()), blockTexture(BdBlocks.TUFF_3.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_4.get(), blockTexture(BdBlocks.TUFF_4.get()), blockTexture(BdBlocks.TUFF_4.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_5.get(), blockTexture(BdBlocks.TUFF_5.get()), blockTexture(BdBlocks.TUFF_5.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_6.get(), blockTexture(BdBlocks.TUFF_6.get()), blockTexture(BdBlocks.TUFF_6.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_7.get(), blockTexture(BdBlocks.TUFF_7.get()), blockTexture(BdBlocks.TUFF_7.get()));
        slabBlock((SlabBlock) BdBlocks.TUFF_SLAB_8.get(), blockTexture(Blocks.TUFF), blockTexture(Blocks.TUFF));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_1.get(), blockTexture(BdBlocks.TUFF_1.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_2.get(), blockTexture(BdBlocks.TUFF_2.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_3.get(), blockTexture(BdBlocks.TUFF_3.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_4.get(), blockTexture(BdBlocks.TUFF_4.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_5.get(), blockTexture(BdBlocks.TUFF_5.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_6.get(), blockTexture(BdBlocks.TUFF_6.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_7.get(), blockTexture(BdBlocks.TUFF_7.get()));
        stairsBlock((StairBlock) BdBlocks.TUFF_STAIRS_8.get(), blockTexture(Blocks.TUFF));

        simpleBlock(BdBlocks.AMETHYST_BLOCK_1.get());
        simpleBlock(BdBlocks.AMETHYST_BLOCK_2.get());
        simpleBlock(BdBlocks.AMETHYST_BLOCK_3.get());
        logBlock((RotatedPillarBlock) BdBlocks.AMETHYST_BLOCK_4.get());
        simpleBlock(BdBlocks.AMETHYST_BLOCK_5.get());
        simpleBlock(BdBlocks.AMETHYST_BLOCK_6.get());
        simpleBlock(BdBlocks.AMETHYST_BLOCK_7.get());
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_1.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_1.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_1.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_2.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_2.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_2.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_3.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_3.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_3.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_4.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_4.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_4.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_5.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_5.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_5.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_6.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_6.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_6.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_7.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_7.get()), blockTexture(BdBlocks.AMETHYST_BLOCK_7.get()));
        slabBlock((SlabBlock) BdBlocks.AMETHYST_SLAB_8.get(), blockTexture(Blocks.AMETHYST_BLOCK), blockTexture(Blocks.AMETHYST_BLOCK));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_1.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_1.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_2.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_2.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_3.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_3.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_4.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_4.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_5.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_5.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_6.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_6.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_7.get(), blockTexture(BdBlocks.AMETHYST_BLOCK_7.get()));
        stairsBlock((StairBlock) BdBlocks.AMETHYST_STAIRS_8.get(), blockTexture(Blocks.AMETHYST_BLOCK));

        horizontalBlock(BdBlocks.INDUSTRIAL_1.get(), blockTexture(BdBlocks.INDUSTRIAL_1.get()), blockTexture(BdBlocks.INDUSTRIAL_1.get()),blockTexture(BdBlocks.INDUSTRIAL_1.get()));
        interactiveBlock((BlockInteractive) BdBlocks.INDUSTRIAL_2.get(), blockTexture(BdBlocks.INDUSTRIAL_2.get()), blockTexture(BdBlocks.INDUSTRIAL_2.get()));
        simpleBlock(BdBlocks.INDUSTRIAL_3.get());
        horizontalBlock(BdBlocks.INDUSTRIAL_4.get(), blockTexture(BdBlocks.INDUSTRIAL_4.get()), blockTexture(BdBlocks.INDUSTRIAL_4.get()),blockTexture(BdBlocks.INDUSTRIAL_4.get()));
        simpleBlock(BdBlocks.INDUSTRIAL_5.get());
        simpleBlock(BdBlocks.INDUSTRIAL_6.get());
        lampBlock((RedstoneLampBlock) BdBlocks.INDUSTRIAL_7.get(), blockTexture(BdBlocks.INDUSTRIAL_7.get()), blockTexture(BdBlocks.INDUSTRIAL_7.get()));
        simpleBlock(BdBlocks.INDUSTRIAL_8.get());

        horizontalBlock(BdBlocks.WARNING_STRIPES_1.get(), blockTexture(BdBlocks.WARNING_STRIPES_1.get()), blockTexture(BdBlocks.WARNING_STRIPES_1.get()),blockTexture(BdBlocks.WARNING_STRIPES_1.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_2.get(), blockTexture(BdBlocks.WARNING_STRIPES_2.get()), blockTexture(BdBlocks.WARNING_STRIPES_2.get()),blockTexture(BdBlocks.WARNING_STRIPES_2.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_3.get(), blockTexture(BdBlocks.WARNING_STRIPES_3.get()), blockTexture(BdBlocks.WARNING_STRIPES_3.get()),blockTexture(BdBlocks.WARNING_STRIPES_3.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_4.get(), blockTexture(BdBlocks.WARNING_STRIPES_4.get()), blockTexture(BdBlocks.WARNING_STRIPES_4.get()),blockTexture(BdBlocks.WARNING_STRIPES_4.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_5.get(), blockTexture(BdBlocks.WARNING_STRIPES_5.get()), blockTexture(BdBlocks.WARNING_STRIPES_5.get()),blockTexture(BdBlocks.WARNING_STRIPES_5.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_6.get(), blockTexture(BdBlocks.WARNING_STRIPES_6.get()), blockTexture(BdBlocks.WARNING_STRIPES_6.get()),blockTexture(BdBlocks.WARNING_STRIPES_6.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_7.get(), blockTexture(BdBlocks.WARNING_STRIPES_7.get()), blockTexture(BdBlocks.WARNING_STRIPES_7.get()),blockTexture(BdBlocks.WARNING_STRIPES_7.get()));
        horizontalBlock(BdBlocks.WARNING_STRIPES_8.get(), blockTexture(BdBlocks.WARNING_STRIPES_8.get()), blockTexture(BdBlocks.WARNING_STRIPES_8.get()),blockTexture(BdBlocks.WARNING_STRIPES_8.get()));

        simpleBlock(BdBlocks.LABORATORY_1.get());
        simpleBlock(BdBlocks.LABORATORY_2.get());
        logBlock((RotatedPillarBlock) BdBlocks.LABORATORY_3.get());
        lampBlock((RedstoneLampBlock) BdBlocks.LABORATORY_4.get(), blockTexture(BdBlocks.LABORATORY_4.get()), blockTexture(BdBlocks.LABORATORY_4.get()));
    }
}
