package com.tynoxs.buildersdelight.datagen.providers;

import com.tynoxs.buildersdelight.BuildersDelight;
import com.tynoxs.buildersdelight.content.init.BdBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class BdItemTagProvider extends ItemTagsProvider {
    public BdItemTagProvider(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> future,
                             CompletableFuture<TagLookup<Block>> completableFuture, @Nullable ExistingFileHelper existingFileHelper) {
        super(packOutput, future, completableFuture, BuildersDelight.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {

        this.tag(ItemTags.LOGS_THAT_BURN)
                .add(BdBlocks.ACACIA_PLANKS_1.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_2.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_3.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_4.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_5.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_6.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_7.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_1.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_2.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_3.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_4.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_5.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_6.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_7.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_1.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_2.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_3.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_4.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_5.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_6.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_7.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_1.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_2.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_3.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_4.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_5.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_6.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_7.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_1.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_2.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_3.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_4.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_5.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_6.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_7.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_1.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_2.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_3.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_4.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_5.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_6.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_7.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_7.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_1.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_2.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_3.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_4.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_5.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_6.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_7.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_1.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_2.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_3.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_4.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_5.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_6.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_7.get().asItem())
                .add(BdBlocks.OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.OAK_PLANKS_7.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_1.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_2.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_3.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_4.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_5.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_6.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_7.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_1.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_2.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_3.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_4.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_5.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_6.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_7.get().asItem());

        this.tag(ItemTags.PLANKS)
                .add(BdBlocks.ACACIA_PLANKS_1.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_2.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_3.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_4.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_5.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_6.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_7.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_1.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_2.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_3.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_4.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_5.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_6.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_7.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_1.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_2.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_3.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_4.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_5.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_6.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_7.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_1.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_2.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_3.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_4.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_5.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_6.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_7.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_1.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_2.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_3.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_4.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_5.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_6.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_7.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_1.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_2.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_3.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_4.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_5.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_6.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_7.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_7.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_1.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_2.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_3.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_4.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_5.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_6.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_7.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_1.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_2.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_3.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_4.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_5.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_6.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_7.get().asItem())
                .add(BdBlocks.OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.OAK_PLANKS_7.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_1.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_2.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_3.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_4.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_5.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_6.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_7.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_1.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_2.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_3.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_4.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_5.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_6.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_7.get().asItem());

        this.tag(ItemTags.PLANKS)
                .add(BdBlocks.ACACIA_PLANKS_1.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_2.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_3.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_4.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_5.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_6.get().asItem())
                .add(BdBlocks.ACACIA_PLANKS_7.get().asItem())

                .add(BdBlocks.BIRCH_PLANKS_1.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_2.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_3.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_4.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_5.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_6.get().asItem())
                .add(BdBlocks.BIRCH_PLANKS_7.get().asItem())

                .add(BdBlocks.BAMBOO_PLANKS_1.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_2.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_3.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_4.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_5.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_6.get().asItem())
                .add(BdBlocks.BAMBOO_PLANKS_7.get().asItem())

                .add(BdBlocks.CHERRY_PLANKS_1.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_2.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_3.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_4.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_5.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_6.get().asItem())
                .add(BdBlocks.CHERRY_PLANKS_7.get().asItem())

                .add(BdBlocks.CRIMSON_PLANKS_1.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_2.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_3.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_4.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_5.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_6.get().asItem())
                .add(BdBlocks.CRIMSON_PLANKS_7.get().asItem())

                .add(BdBlocks.DARK_OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.DARK_OAK_PLANKS_7.get().asItem())

                .add(BdBlocks.JUNGLE_PLANKS_1.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_2.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_3.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_4.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_5.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_6.get().asItem())
                .add(BdBlocks.JUNGLE_PLANKS_7.get().asItem())

                .add(BdBlocks.MANGROVE_PLANKS_1.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_2.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_3.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_4.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_5.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_6.get().asItem())
                .add(BdBlocks.MANGROVE_PLANKS_7.get().asItem())

                .add(BdBlocks.OAK_PLANKS_1.get().asItem())
                .add(BdBlocks.OAK_PLANKS_2.get().asItem())
                .add(BdBlocks.OAK_PLANKS_3.get().asItem())
                .add(BdBlocks.OAK_PLANKS_4.get().asItem())
                .add(BdBlocks.OAK_PLANKS_5.get().asItem())
                .add(BdBlocks.OAK_PLANKS_6.get().asItem())
                .add(BdBlocks.OAK_PLANKS_7.get().asItem())

                .add(BdBlocks.SPRUCE_PLANKS_1.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_2.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_3.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_4.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_5.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_6.get().asItem())
                .add(BdBlocks.SPRUCE_PLANKS_7.get().asItem())

                .add(BdBlocks.WARPED_PLANKS_1.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_2.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_3.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_4.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_5.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_6.get().asItem())
                .add(BdBlocks.WARPED_PLANKS_7.get().asItem());

        this.tag(ItemTags.WOODEN_STAIRS)
                .add(BdBlocks.ACACIA_STAIRS_1.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_2.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_3.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_4.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_5.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_6.get().asItem())
                .add(BdBlocks.ACACIA_STAIRS_7.get().asItem())

                .add(BdBlocks.BIRCH_STAIRS_1.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_2.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_3.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_4.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_5.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_6.get().asItem())
                .add(BdBlocks.BIRCH_STAIRS_7.get().asItem())

                .add(BdBlocks.BAMBOO_STAIRS_1.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_2.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_3.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_4.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_5.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_6.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_7.get().asItem())

                .add(BdBlocks.CHERRY_STAIRS_1.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_2.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_3.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_4.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_5.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_6.get().asItem())
                .add(BdBlocks.CHERRY_STAIRS_7.get().asItem())

                .add(BdBlocks.CRIMSON_STAIRS_1.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_2.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_3.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_4.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_5.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_6.get().asItem())
                .add(BdBlocks.CRIMSON_STAIRS_7.get().asItem())

                .add(BdBlocks.DARK_OAK_STAIRS_1.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_2.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_3.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_4.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_5.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_6.get().asItem())
                .add(BdBlocks.DARK_OAK_STAIRS_7.get().asItem())

                .add(BdBlocks.JUNGLE_STAIRS_1.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_2.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_3.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_4.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_5.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_6.get().asItem())
                .add(BdBlocks.JUNGLE_STAIRS_7.get().asItem())

                .add(BdBlocks.MANGROVE_STAIRS_1.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_2.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_3.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_4.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_5.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_6.get().asItem())
                .add(BdBlocks.MANGROVE_STAIRS_7.get().asItem())

                .add(BdBlocks.OAK_STAIRS_1.get().asItem())
                .add(BdBlocks.OAK_STAIRS_2.get().asItem())
                .add(BdBlocks.OAK_STAIRS_3.get().asItem())
                .add(BdBlocks.OAK_STAIRS_4.get().asItem())
                .add(BdBlocks.OAK_STAIRS_5.get().asItem())
                .add(BdBlocks.OAK_STAIRS_6.get().asItem())
                .add(BdBlocks.OAK_STAIRS_7.get().asItem())

                .add(BdBlocks.SPRUCE_STAIRS_1.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_2.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_3.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_4.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_5.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_6.get().asItem())
                .add(BdBlocks.SPRUCE_STAIRS_7.get().asItem())

                .add(BdBlocks.WARPED_STAIRS_1.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_2.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_3.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_4.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_5.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_6.get().asItem())
                .add(BdBlocks.WARPED_STAIRS_7.get().asItem());

        this.tag(ItemTags.WOODEN_SLABS)
                .add(BdBlocks.ACACIA_SLAB_1.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_2.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_3.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_4.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_5.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_6.get().asItem())
                .add(BdBlocks.ACACIA_SLAB_7.get().asItem())

                .add(BdBlocks.BIRCH_SLAB_1.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_2.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_3.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_4.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_5.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_6.get().asItem())
                .add(BdBlocks.BIRCH_SLAB_7.get().asItem())

                .add(BdBlocks.BAMBOO_STAIRS_1.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_2.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_3.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_4.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_5.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_6.get().asItem())
                .add(BdBlocks.BAMBOO_STAIRS_7.get().asItem())

                .add(BdBlocks.CHERRY_SLAB_1.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_2.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_3.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_4.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_5.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_6.get().asItem())
                .add(BdBlocks.CHERRY_SLAB_7.get().asItem())

                .add(BdBlocks.CRIMSON_SLAB_1.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_2.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_3.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_4.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_5.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_6.get().asItem())
                .add(BdBlocks.CRIMSON_SLAB_7.get().asItem())

                .add(BdBlocks.DARK_OAK_SLAB_1.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_2.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_3.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_4.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_5.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_6.get().asItem())
                .add(BdBlocks.DARK_OAK_SLAB_7.get().asItem())

                .add(BdBlocks.JUNGLE_SLAB_1.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_2.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_3.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_4.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_5.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_6.get().asItem())
                .add(BdBlocks.JUNGLE_SLAB_7.get().asItem())

                .add(BdBlocks.MANGROVE_SLAB_1.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_2.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_3.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_4.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_5.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_6.get().asItem())
                .add(BdBlocks.MANGROVE_SLAB_7.get().asItem())

                .add(BdBlocks.OAK_SLAB_1.get().asItem())
                .add(BdBlocks.OAK_SLAB_2.get().asItem())
                .add(BdBlocks.OAK_SLAB_3.get().asItem())
                .add(BdBlocks.OAK_SLAB_4.get().asItem())
                .add(BdBlocks.OAK_SLAB_5.get().asItem())
                .add(BdBlocks.OAK_SLAB_6.get().asItem())
                .add(BdBlocks.OAK_SLAB_7.get().asItem())

                .add(BdBlocks.SPRUCE_SLAB_1.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_2.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_3.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_4.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_5.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_6.get().asItem())
                .add(BdBlocks.SPRUCE_SLAB_7.get().asItem())

                .add(BdBlocks.WARPED_SLAB_1.get().asItem())
                .add(BdBlocks.WARPED_SLAB_2.get().asItem())
                .add(BdBlocks.WARPED_SLAB_3.get().asItem())
                .add(BdBlocks.WARPED_SLAB_4.get().asItem())
                .add(BdBlocks.WARPED_SLAB_5.get().asItem())
                .add(BdBlocks.WARPED_SLAB_6.get().asItem())
                .add(BdBlocks.WARPED_SLAB_7.get().asItem());
    }

    @Override
    public String getName() {
        return "Item Tags";
    }
}
