name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle


      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon


      - name: Generate release notes
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          awk -v tag="$VERSION" '
          $0 ~ "^## "tag"$" {flag=1; next}
          /^## / && flag {exit}
          flag {print}
          ' CHANGES.md > RELEASE.md


      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.ref_name }} release"
          draft: true
          body_path: RELEASE.md
          files: |
            build/libs/*.jar